### ISSUE TITLE
Outdated version in central NPM repository

### ISSUE THREAD

**Issue by ViLPy** [gemini-testing/hermione#104]
Hi, I noticed that the latest version which can be installed with ```npm i hermione``` is 0.20.0

Of course it is possible to use latest one just by fetching sources from github, but it's nice to sync releases with central NPM repository. At the moment if someone will follow quick start guide on github it wouldn't work because of difference between versions.

**Comment by sipayRT** [comment]
hi. we will publish new version soon. You can use latest `next` tag by `npm i hermione@0.23.0` but this version is on testing now

**Comment by sipayRT** [comment]
v0.23.0 was published
