### ISSUE TITLE
Outdated dependency: webdriverio

### ISSUE THREAD

**Issue by fobos** [gemini-testing/hermione#205]
Hi. Will you update your fork of webdriverio dependency? Original package contains lots of fixes.

**Comment by j0tunn** [comment]
@fobos we plan to go to upstream in a few weeks.

**Comment by fobos** [comment]
@j0tunn thanks for quick response.

I faced with https://github.com/webdriverio/webdriverio/issues/2475 that existed in version 4.9.9 and fixed in https://github.com/webdriverio/webdriverio/pull/2486 and released in 4.9.11

**Comment by loyd** [comment]
What is the status of this issue?

**Comment by j0tunn** [comment]
`hermione@0.55.0`
