### ISSUE TITLE
How to debug integration tests?

### ISSUE THREAD

**Issue by tarmolov** [gemini-testing/hermione#21]
When my test fails, I want to investigate what is wrong, opening a browser and checking a current state with devtools.

Webdriver.io has a [debug method](http://webdriver.io/api/utility/debug.html) but the hermione doesn't. Could you suggest how to do a right debugging with hermione? It'd be great to have a documentation about it. It's a very important topic for the future clients.

**Comment by arikon** [comment]
@tarmolov `this.browser` in hermione tests is an unaltered webdriver.io client. It should work out of the box.

**Comment by tarmolov** [comment]
Yeah. I've already realized that. Thx :)
