### ISSUE TITLE
Error on installing the package

### ISSUE THREAD

**Issue by Phenomen** [gemini-testing/hermione#216]
```
>npm install -g hermione
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: webdriverio@github:gemini-testing/webdriverio#master.
npm ERR! package.json npm can't find a package.json file in your current directory.
```
```
>node -v
v9.4.0
>npm -v
5.6.0
```
Windows 10 64bit
[2018-01-30T12_49_51_333Z-debug.log](https://github.com/gemini-testing/hermione/files/1677698/2018-01-30T12_49_51_333Z-debug.log)

**Comment by j0tunn** [comment]
Try now. I've updated `latest` tag.
Or try to install `hermione@0.56.1`

**Comment by Phenomen** [comment]
Now it's stuck at:
>Non-registry package missing package.json: webdriverio@github:gemini-testing/webdriverio#fix.opera.

I've made local repo copy with some fixes in package.json:
"webdriverio": "^4.10.1",
"worker-farm": "^1.5.2"

After that I was able to install just fine.

**Comment by j0tunn** [comment]
hermione will not be working with `worker-farm@1.5.2`. There is some extra functionality in our fork.
