### ISSUE TITLE
How to set up WebdriverIO config?

### ISSUE THREAD

**Issue by kopylovvlad** [gemini-testing/hermione#238]
When I run test, I see a lot of warnings like:

> (You can disable this warning by setting `"deprecationWarnings": false` in your WebdriverIO config)
> WARNING: the "doDoubleClick" command will be deprecated soon. If you have further questions, reach out in the WebdriverIO Gitter support channel (https://gitter.im/webdriverio/webdriverio).
> Note: This command is not part of the W3C WebDriver spec and won't be supported in future versions of the driver. It is recommended to just call the click command on the same element twice in the row.
> 

I tried to create file wdio.conf.js with
```javascript
module.exports = {
  deprecationWarnings: false
}
```
But is does not work.

hermione verion - 0.62.0

**Comment by sipayRT** [comment]
hi

> I tried to create file wdio.conf.js with

hermione has own config and use wdio with API. So your config will not be used. Unfortunately, we haven't added ability to overwrite all wdio options yet.
