### ISSUE TITLE
Override hermione config with --conf

### ISSUE THREAD

**Issue by alex-nask** [gemini-testing/hermione#248]
При попытке указать кастомный конфиг через --conf
```
hermione --conf hermione/.hermione.custom.conf.js
```
пытается искать дефолтный кофиг
```
Unable to read config from path .hermione.conf.js
```
Версия hermione - 0.65.2

**Comment by sipayRT** [comment]
ты неправильно указал название опции `--config`

**Comment by j0tunn** [comment]
Попробуй `--config` или `-c`.
Используй `--help` для того чтобы узнать все доступные опции

**Comment by alex-nask** [comment]
```
