### ISSUE TITLE
Вопросы по поддержке hermione

### ISSUE THREAD

**Issue by FryOS** [gemini-testing/hermione#293]
Я не знаю куда вам можно еще написать чтобы быть услышанным, простите если это не то место. Скажите и я удалю этот запрос.  К сожалению gitter я не нашел посвященный hermione, на youtube канале пока нет ответов. 
1. У вас есть в планах провести курс лекций(вводный курс или продвинутый) по hermione для новичков/опытных разработчиков?
2. будет ли создан чат, может тот же gitter или slack(другие аналоги) использовать, где все смогут общаться и задавать вопросы и делится своими примерами кода.

**Comment by sipayRT** [comment]
Привет

Нет, в планах у нас нет никаких курсов/лекций. Насчет чата можно подумать, но это на самом деле можно сделать и без нашего участия - можно будет пост-фактум позвать и нас в этот чат.

Вопросы можно задавать и в текущем формате через issues - так он точно не потеряется среди сообщений в том же чате

> на youtube канале пока нет ответов

а что за канал? мы никакой не заводили. Поделись ссылкой, плз

**Comment by FryOS** [comment]
Я скорее всего не так выразился. Канал на самом деле, как я понял, причастен к Фронтенд разработке ШРИ. Это сам канал https://www.youtube.com/channel/UCMtlICYxr6Dz_PG9_SVqRYQ
А это видео, которое я смотрел. 
> а что за канал? мы никакой не заводили. Поделись ссылкой, плз

https://youtu.be/dflmpqh_oRc
> Нет, в планах у нас нет никаких курсов/лекций

Жаль. Но спасибо за ответ и такое быстрое реагирование =) Не ожидал. 
На счет чата, было бы круто. Успехов!

**Comment by DudaGod** [comment]
Итого: если есть вопросы заводите issue постараемся ответить. Никакого отдельного чата у нас все еще нет.
