### ISSUE TITLE
Вопрос про PAGE OBJECT и как получить данные из console в запущенном браузере

### ISSUE THREAD

**Issue by FryOS** [gemini-testing/hermione#294]
Вопросы:
1. Я правильно понимаю: что PAGE OBJECT PATTERN также можно использовать и с hermione 
То есть как это описано у webdriverIO http://webdriver.io/guide/testrunner/pageobjects.html
Так же  создаю классы, расписываю методы и дальше использую их ?
2. Я провожу тест где я сначала подписываюсь на события window.App.EventEmitter, далее заполняю поля формы и кликаю на кнопку для шага вперед. В console  в запущенном браузере у меня эти данные попадают и я могу их просмотреть. Вы не подскажите как мне эти данные достать(пробросить в сам тест) и получить их уже в консоле моей IDE , либо лучше вариант сделать assert на них, ну то есть проверить что я получаю те данные что и указывал при заполнении. То есть, если они будут равны, то тест прошел, нет - то провал. 
Простите если неправильно подал информацию. Если нужно то могу прислать свой небольшой код теста, для понимания.  
Спасибо.

**Comment by sipayRT** [comment]
1. Да, все верно
2. Тебе не нужно проверять значения в console - в этом нет смысла. Проверяй именно значения/поведение.
