### ISSUE TITLE
Не удается использовать метод assertView

### ISSUE THREAD

**Issue by h23github** [gemini-testing/hermione#313]
Пытаюсь делать как в примере из Readme - выскакивает AssertViewError. Покопавшись в коде гермионы выяснил, что его вызывает NoRefImageError, который появляется из-за того что в дефолтной директории (/hermione/screens) нет нужных скринов:
can not find reference image at  D:\ ... \hermione\screens\2de3131\chrome\body.png for "body" state

По Readme совершенно не понятно, откуда они должны браться. Сперва думал что как в gemini, при первом запуске собираются, а при повторном сравниваются - но видимо нет. В примере нет никакого намека на отдельное сохранение скриншотов.

Еще занимаясь дебагом этой проблемы заметил, что screenshotPath не подхватыватся из конфига методом, выводящим ошибку (пробовал и без этого параметра конфигурации, и с ним - путь к скринам в ошибке не меняется).

В общем был бы рад пояснениям, как этим методом пользоваться.

**Comment by eGavr** [comment]
Здравствуй!

> Сперва думал что как в gemini, при первом запуске собираются, а при повторном сравниваются - но видимо нет

В gemini не так работает. В gemini сначала необходимо запустить инструмент: 

```
gemini update
```

И эта команда сохранит эталонные скриншоты

А затем необходимо выполнить 

```
gemini test
```

В случае с hermione неоьходимо использовать опции `--update-refs`.
Тогда инструмент снимет эталонные скриншоты. 
Затем уже можно запускать без этой опции.

Вообще вместо опции `--update-refs` лучше использовать `hermione gui`, который подключается как [плагин](https://github.com/gemini-testing/html-reporter).

Вот документация [как подключать плагины](https://github.com/gemini-testing/hermione#plugins).

**Comment by eGavr** [comment]
> Еще занимаясь дебагом этой проблемы заметил, что screenshotPath не подхватыватся из конфига методом, выводящим ошибку (пробовал и без этого параметра конфигурации, и с ним - путь к скринам в ошибке не меняется).

Тут нужен минимально воспроизводимый кейс проблемы, чтобы нам легче было воспроизвести, где описано текущее поведение и ожидаемое.

**Comment by h23github** [comment]
Привет. Спасибо за быстрый отклик.

> gemini update
Да, знаю, c gemini так и делал. А с гермионой не нашел информации как нужно, так тоже пробовал - не прокатило.

> В случае с hermione необходимо использовать опции `--update-refs`.
Вот этого не знал. Неплохо было бы это в README добавить.

> Вообще вместо опции `--update-refs` лучше использовать `hermione gui`, который подключается как [плагин](https://github.com/gemini-testing/html-reporter).

А html-reporter я уже подключал к gemini, когда пробовал этот фреймворк.
Т.е. само подключение его как плагина убирает необходимость передавать опцию `--update-refs`?

> Тут нужен минимально воспроизводимый кейс проблемы
В общем попробую завтра с опцией, возможно проблема только в недостатке документации.

**Comment by h23github** [comment]
> нужен минимально воспроизводимый кейс проблемы

Вот мой файл конфигурации (.hermione.conf.js в корне проекта):

module.exports = {
  sets: {
    all: {
      files: 'test/hermione/spec/**/*.spec.js'
    }
  },

  baseUrl: 'http://localhost:8080',
  waitTimeout: 10000,
  screenshotPath: 'test/screens',

  browsers: {
    chrome: {
      desiredCapabilities: {
        browserName: 'chrome'
      }
    }
  },

};

Теперь все работает нормально, но скриншоты попадают в директорию hermione в корне проекта, а не в папку test.

Гермиону установил локально, запускаю командой node node_modules/hermione/bin/hermione --update-refs

**Comment by eGavr** [comment]
> Вот этого не знал. Неплохо было бы это в README добавить.

Приносим извинения за сырую документацию, в ближайшее время добавим.

> А html-reporter я уже подключал к gemini, когда пробовал этот фреймворк.
Т.е. само подключение его как плагина убирает необходимость передавать опцию --update-refs?

Да, при использовании команды `gui` из плагина `html-reporter` можно не запускать `hermione` с опцией `--update-refs`. Скажем так.. одновременное использование этой опции и `gui` будет конфликтовать, так как `--update-refs` будет иметь больший приоритет и при запуске `gui` тесты всегда будут проходить, а скриншоты пересниматься безусловно. `gui` же позволяет предварительно посмотреть глазами, что будет сохранено в качестве эталона.

> Теперь все работает нормально, но скриншоты попадают в директорию hermione в корне проекта, а не в папку test.

Еще раз приношу извинения, что в доке этого не было.

В конфиге выше вижу, что используется `screenshotPath`. Эта опция по смыслу отвечает не за то, куда будут сохраняться эталоны, а за то, куда будут сохраняться скриншоты при вызове метода `saveScreenshot` в тесте (к методу `assertView` он не имеет никакого отношения, этот метод просто снимает скриншот).

Чтобы сконфигурировать сохранение скриншотов в определенную папку, необходимо использовать опцию `screenshotsDir`, которая может принимать строку или функцию.

**Comment by h23github** [comment]
Большое спасибо за пояснения.
Рад что помог вам улучшить документацию, фреймворк у вас очень удобный, если знать все тонкости)

**Comment by eGavr** [comment]
https://github.com/gemini-testing/hermione/pull/316
