### ISSUE TITLE
Не работает assertView

### ISSUE THREAD

**Issue by dizel3d** [gemini-testing/hermione#314]
Вот пример https://github.com/dizel3d/hermione-test
`hermione --update-refs` не генерирует эталоны
`hermione` говорит, что тесты проходят, даже когда  assertView натравлен на отсутствующий элемент.
`screenshotDelay` не выдерживается.

node v8.4.0, macos 10.13.6

**Comment by j0tunn** [comment]
В тесте нужно дописать `return` или `await`

**Comment by dizel3d** [comment]
@j0tunn точняк! Спасибо!
