### ISSUE TITLE
Random crush

### ISSUE THREAD

**Issue by mrquokka** [gemini-testing/hermione#315]
Sometime random browser test is crushed:
✓ mocha no_failures [internet_explorer:c728732d-efd0-4c5a-ab36-5839c8fd0693] - 3618ms
✘ mocha no_failures [chrome:65481dee14146e30c9d85fc6fc94df0c] - 1870ms
✓ mocha no_failures [firefox:82fd7059-e951-4d99-a749-b9fd36809f80] - 5771ms

It may be ie/chrome/firefox, if i restart test it will work again

Hermione config is 
```
module.exports = {
    sets: {
        desktop: {
            files: 'hermione_tests'
        }
    },

    browsers: {
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome'
            }
        }
        ,
        firefox: {
            desiredCapabilities: {
                browserName: 'firefox'
            }
        }
        ,
        internet_explorer: {
            desiredCapabilities: {
                browserName: 'internet explorer'
            }
        }
    },
    gridUrl: "http://192.168.8.22:4444/wd/hub"
};

```
i have only one test - check mocha tests result on terminal
```
var assert = require('chai').assert;
describe('mocha', function() {
    it('no_failures', function() {
        return this.browser
            .url('http://192.168.8.21:5000/tests')
            .getText('.failures')
            .then(function(title) {
                assert.equal(title, 'failures: 0')
            });
    });
});
```

**Comment by mrquokka** [comment]
I tried to test on local ubuntu, remote ubuntu, remote window selenium-standalone servers and it crushed anyway

**Comment by j0tunn** [comment]
Hi. Can you provide full test output with error message and stacktrace?

**Comment by mrquokka** [comment]
Firefox failed

`
C:\selenium>java.exe -Xrs -jar selenium-server-standalone-3.14.0.jar -port 4444
12:00:42.777 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.14.
0', revision: 'aacccce0'
12:00:42.777 INFO [GridLauncherV3$1.launch] - Launching a standalone Selenium Se
rver on port 4444
2018-10-01 12:00:43.042:INFO::main: Logging initialized @628ms to org.seleniumhq
.jetty9.util.log.StdErrLog
12:00:43.339 INFO [SeleniumServer.boot] - Selenium Server is up and running on p
ort 4444
12:00:47.089 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "firefox",
  "handlesAlerts": true,
  "javascriptEnabled": true,
  "locationContextEnabled": true,
  "loggingPrefs": {
    "browser": "ALL",
    "driver": "ALL"
  },
  "requestOrigins": {
    "url": "http:\u002f\u002fwebdriver.io",
    "version": "4.13.2",
    "name": "webdriverio"
  },
  "rotatable": true
}
12:00:47.089 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.o
penqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selen
ium.firefox.GeckoDriverService)
12:00:47.089 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "handlesAlerts": true,
  "javascriptEnabled": true,
  "locationContextEnabled": true,
  "loggingPrefs": {
    "browser": "ALL",
    "driver": "ALL"
  },
  "requestOrigins": {
    "url": "http:\u002f\u002fwebdriver.io",
    "version": "4.13.2",
    "name": "webdriverio"
  },
  "rotatable": true
}
12:00:47.089 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.o
penqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selen
ium.chrome.ChromeDriverService)
12:00:47.074 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "internet explorer",
  "handlesAlerts": true,
  "javascriptEnabled": true,
  "locationContextEnabled": true,
  "loggingPrefs": {
    "browser": "ALL",
    "driver": "ALL"
  },
  "requestOrigins": {
    "url": "http:\u002f\u002fwebdriver.io",
    "version": "4.13.2",
    "name": "webdriverio"
  },
  "rotatable": true
}
12:00:47.105 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.o
penqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selen
ium.ie.InternetExplorerDriverService)
1538384447152   geckodriver     INFO    geckodriver 0.21.0
1538384447167   geckodriver     INFO    Listening on 127.0.0.1:6399
Started InternetExplorerDriver server (64-bit)
3.14.0.0
Listening on port 41686
Only local connections are allowed
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on
port 18644
Only local connections are allowed.
1538384447949   mozrunner::runner       INFO    Running command: "C:\\Program Fi
les\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-pr
ofile" "C:\\Users\\dev\\AppData\\Local\\Temp\\rust_mozprofile.aHGnYwiPATjl"
12:00:48.700 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
12:00:48.715 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started ne
w session af082b76-4bc0-4083-8d58-6785ee41636f (org.openqa.selenium.ie.InternetE
xplorerDriverService)
12:00:49.637 INFO [ActiveSessions$1.onStop] - Removing session af082b76-4bc0-408
3-8d58-6785ee41636f (org.openqa.selenium.ie.InternetExplorerDriverService)
12:00:51.095 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
1538384451227   Marionette      INFO    Listening on port 59249
12:00:51.435 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started ne
w session 6a5204deee650f7096edf3de4dceda32 (org.openqa.selenium.chrome.ChromeDri
verService)
12:00:51.519 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
12:00:51.527 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started ne
w session c2624ada-a386-40db-83ac-6232006ccf7d (org.openqa.selenium.firefox.Geck
oDriverService)
12:00:51.982 INFO [ActiveSessions$1.onStop] - Removing session 6a5204deee650f709
6edf3de4dceda32 (org.openqa.selenium.chrome.ChromeDriverService)
Unable to read VR Path Registry from C:\Users\dev\AppData\Local\openvr\openvrpat
hs.vrpath
[Child 5136, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/s
rc/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\dev\AppData\Local\openvr\openvrpat
hs.vrpath
[Child 6844, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/s
rc/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\dev\AppData\Local\openvr\openvrpat
hs.vrpath
[Child 5324, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/s
rc/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\dev\AppData\Local\openvr\openvrpat
hs.vrpath
[Parent 3304, Gecko_IOThread] WARNING: file z:/build/build/src/ipc/chromium/src/
base/process_util_win.cc, line 188
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notifi
cation. Ignoring timer registration for id: telemetry_modules_ping
12:00:57.794 INFO [ActiveSessions$1.onStop] - Removing session c2624ada-a386-40d
b-83ac-6232006ccf7d (org.openqa.selenium.firefox.GeckoDriverService)
`

**Comment by mrquokka** [comment]
Firefox Failed

```
C:\selenium>java.exe -Xrs -jar selenium-server-standalone-3.14.0.jar -port 4444
12:00:42.777 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.14.
0', revision: 'aacccce0'
12:00:42.777 INFO [GridLauncherV3$1.launch] - Launching a standalone Selenium Se
rver on port 4444
2018-10-01 12:00:43.042:INFO::main: Logging initialized @628ms to org.seleniumhq
.jetty9.util.log.StdErrLog
12:00:43.339 INFO [SeleniumServer.boot] - Selenium Server is up and running on p
ort 4444
12:00:47.089 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "firefox",
  "handlesAlerts": true,
  "javascriptEnabled": true,
  "locationContextEnabled": true,
  "loggingPrefs": {
    "browser": "ALL",
    "driver": "ALL"
  },
  "requestOrigins": {
    "url": "http:\u002f\u002fwebdriver.io",
    "version": "4.13.2",
    "name": "webdriverio"
  },
  "rotatable": true
}
12:00:47.089 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.o
penqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selen
ium.firefox.GeckoDriverService)
12:00:47.089 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "handlesAlerts": true,
  "javascriptEnabled": true,
  "locationContextEnabled": true,
  "loggingPrefs": {
    "browser": "ALL",
    "driver": "ALL"
  },
  "requestOrigins": {
    "url": "http:\u002f\u002fwebdriver.io",
    "version": "4.13.2",
    "name": "webdriverio"
  },
  "rotatable": true
}
12:00:47.089 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.o
penqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selen
ium.chrome.ChromeDriverService)
12:00:47.074 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "internet explorer",
  "handlesAlerts": true,
  "javascriptEnabled": true,
  "locationContextEnabled": true,
  "loggingPrefs": {
    "browser": "ALL",
    "driver": "ALL"
  },
  "requestOrigins": {
    "url": "http:\u002f\u002fwebdriver.io",
    "version": "4.13.2",
    "name": "webdriverio"
  },
  "rotatable": true
}
12:00:47.105 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.o
penqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selen
ium.ie.InternetExplorerDriverService)
1538384447152   geckodriver     INFO    geckodriver 0.21.0
1538384447167   geckodriver     INFO    Listening on 127.0.0.1:6399
Started InternetExplorerDriver server (64-bit)
3.14.0.0
Listening on port 41686
Only local connections are allowed
Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on
port 18644
Only local connections are allowed.
1538384447949   mozrunner::runner       INFO    Running command: "C:\\Program Fi
les\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-pr
ofile" "C:\\Users\\dev\\AppData\\Local\\Temp\\rust_mozprofile.aHGnYwiPATjl"
12:00:48.700 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
12:00:48.715 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started ne
w session af082b76-4bc0-4083-8d58-6785ee41636f (org.openqa.selenium.ie.InternetE
xplorerDriverService)
12:00:49.637 INFO [ActiveSessions$1.onStop] - Removing session af082b76-4bc0-408
3-8d58-6785ee41636f (org.openqa.selenium.ie.InternetExplorerDriverService)
12:00:51.095 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
1538384451227   Marionette      INFO    Listening on port 59249
12:00:51.435 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started ne
w session 6a5204deee650f7096edf3de4dceda32 (org.openqa.selenium.chrome.ChromeDri
verService)
12:00:51.519 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
12:00:51.527 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started ne
w session c2624ada-a386-40db-83ac-6232006ccf7d (org.openqa.selenium.firefox.Geck
oDriverService)
12:00:51.982 INFO [ActiveSessions$1.onStop] - Removing session 6a5204deee650f709
6edf3de4dceda32 (org.openqa.selenium.chrome.ChromeDriverService)
Unable to read VR Path Registry from C:\Users\dev\AppData\Local\openvr\openvrpat
hs.vrpath
[Child 5136, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/s
rc/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\dev\AppData\Local\openvr\openvrpat
hs.vrpath
[Child 6844, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/s
rc/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\dev\AppData\Local\openvr\openvrpat
hs.vrpath
[Child 5324, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/s
rc/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\dev\AppData\Local\openvr\openvrpat
hs.vrpath
[Parent 3304, Gecko_IOThread] WARNING: file z:/build/build/src/ipc/chromium/src/
base/process_util_win.cc, line 188
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notifi
cation. Ignoring timer registration for id: telemetry_modules_ping
12:00:57.794 INFO [ActiveSessions$1.onStop] - Removing session c2624ada-a386-40d
b-83ac-6232006ccf7d (org.openqa.selenium.firefox.GeckoDriverService)

```

**Comment by j0tunn** [comment]
This is selenium-standalone output. Could you please provide full hermione output

**Comment by mrquokka** [comment]
==HERMIONE==
✓ mocha no_failures [internet_explorer:3ba1f838-9a6b-485f-85b5-650d7090e2a2] - 1615ms
✓ mocha no_failures [chrome:e92f3a4cac2b7b58556d54c46aa2f7ad] - 334ms
✘ mocha no_failures [firefox:b31ea7f3-cd21-4d38-a130-9a9863ac5d3d] - 5725ms
Total: 3 Passed: 2 Failed: 1 Pending: 0 Retries: 0

1) mocha no_failures
   in file hermione_tests/mocha_tests.js

   firefox
     ✘ Error: An element could not be located on the page using the given search parameters (".failures").
    at elements(".failures") - getText.js:18:17
    at url("http://192.168.8.46:5000/webapp_tests/tests") - browser.js:150:20

Where i can find another logs?

**Comment by mrquokka** [comment]
Now i change script to
```
var assert = require('chai').assert;
describe('mocha', function() {
  it('no_failures', function() {
    this.browser.waitForVisible('.failures', 10000);
    return this.browser
      .url('http://$myhost/webapp_tests/tests')
      .getText('.failures')
      .then(function(title) {
        assert.equal(title, 'failures: 0')
      });
  });
});
```

And error sometimes is 
```
✓ mocha no_failures [chrome:a68689d01e90dc19a456ac791535f21a] - 536ms
✘ mocha no_failures [internet_explorer:cd1bc0cf-c5af-47f4-a125-0346de708478] - 3835ms
✓ mocha no_failures [firefox:1dc3d859-d18e-4016-b112-6790c5073fff] - 5880ms
Total: 3 Passed: 2 Failed: 1 Skipped: 0 Retries: 0

1) mocha no_failures
   in file hermione_tests/mocha_tests.js

   internet_explorer
     ✘ Error: An unknown server-side error occurred while processing the command. (Unable to determine type from: E. Last 1 characters read: E
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'DEV-SELENIUM', ip: '192.168.8.22', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '10.0.2'
Driver info: driver.version: unknown)
    at elementIdDisplayed("0a9a829e-1762-4d23-a3f6-a1f737383b96") - isVisible.js:71:55

WARN: Failed to take screenshot on reject: Error: Unable to determine type from: E. Last 1 characters read: E
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'DEV-SELENIUM', ip: '192.168.8.22', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '10.0.2'
```
or

```
✓ mocha no_failures [chrome:880e23d07d5240e7dd2ebdc8aa3813c4] - 487ms
✓ mocha no_failures [firefox:7b8eb6b1-aab6-4945-a9a8-a4f465e9171e] - 5798ms
✘ mocha no_failures [internet_explorer:c69efd81-14c6-43a5-a687-f9402ea4433b] - 10711ms
Total: 3 Passed: 2 Failed: 1 Skipped: 0 Retries: 0

1) mocha no_failures
   in file hermione_tests/mocha_tests.js

   internet_explorer
     ✘ Error: An unknown server-side error occurred while processing the command. (Unable to determine type from: E. Last 1 characters read: E
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'DEV-SELENIUM', ip: '192.168.8.22', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '10.0.2'
Driver info: driver.version: unknown)
    at elementIdDisplayed("7584858f-f4ce-4f42-8c1c-91f2cee64d73") - isVisible.js:71:55

```
or
```
✘ mocha no_failures [internet_explorer:e8195b1b-c435-4014-97ef-b04973655a12] - 1956ms
✓ mocha no_failures [chrome:10519a69a79e53d8ae75f5333a0610dc] - 546ms
✘ mocha no_failures [firefox:0f688888-02ee-4405-bb5a-85aad368a525] - 5782ms
Total: 3 Passed: 1 Failed: 2 Skipped: 0 Retries: 0

1) mocha no_failures
   in file hermione_tests/mocha_tests.js

   internet_explorer
     ✘ AssertionError: expected [ Array(1) ] to equal 'failures: 0'
    at Object.<anonymous> (/hdd/work/projects/py3/hermione_tests/mocha_tests.js:9:16)
    at Object.exec (/usr/local/lib/node_modules/hermione/node_modules/@gemini-testing/webdriverio/build/lib/helpers/safeExecute.js:28:24)
    at Object.resolve (/usr/local/lib/node_modules/hermione/node_modules/@gemini-testing/webdriverio/build/lib/webdriverio.js:191:29)
    at /usr/local/lib/node_modules/hermione/node_modules/@gemini-testing/webdriverio/build/lib/webdriverio.js:540:32
    at _fulfilled (/usr/local/lib/node_modules/hermione/node_modules/@gemini-testing/webdriverio/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/hermione/node_modules/@gemini-testing/webdriverio/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/hermione/node_modules/@gemini-testing/webdriverio/node_modules/q/q.js:816:13)
    at /usr/local/lib/node_modules/hermione/node_modules/@gemini-testing/webdriverio/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/hermione/node_modules/@gemini-testing/webdriverio/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/hermione/node_modules/@gemini-testing/webdriverio/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
   firefox
     ✘ Error: An element could not be located on the page using the given search parameters (".failures").
    at elements(".failures") - getText.js:18:17
    at execute("return typeof __geminiCore !== "undefined"? __geminiCore.resetZoom() : {error: "ERRNOFUNC"}") - existing-browser.js:119:30
```

**Comment by j0tunn** [comment]
There are two bugs in your test:
- .waitForVisible is asynchronous and returns promise-like object, so you should wait for it using `await` or `return`
- you should wait for `.failures` element _after_ opening the page
```js
var assert = require('chai').assert;
describe('mocha', function() {
  it('no_failures', function() {
    return this.browser
      .url('http://$myhost/webapp_tests/tests')
      .waitForVisible('.failures', 10000)
      .getText('.failures')
      .then(function(title) {
        assert.equal(title, 'failures: 0')
      });
  });
});
```

**Comment by mrquokka** [comment]
Anyway error raises, different code

```
✓ mocha no_failures [chrome:dacd6ce4a2970fa59a49101ca54808cc] - 1456ms
✓ mocha no_failures [firefox:d080f428-7501-4803-8bbb-ab4c1c74daa1] - 6303ms
✘ mocha no_failures [internet_explorer:ec584262-a5c3-44ee-9a28-780b065a7ce1] - 9610ms
Total: 3 Passed: 2 Failed: 1 Skipped: 0 Retries: 0

1) mocha no_failures
   in file hermione_tests/mocha_tests.js

   internet_explorer
     ✘ Error: An unknown server-side error occurred while processing the command. (Failed to navigate to http://192.168.8.21:5000/webapp_tests/tests. This usually means that a call to the COM method IWebBrowser2::Navigate2() failed.
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'DEV-SELENIUM', ip: '192.168.8.22', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '10.0.2'
Driver info: driver.version: unknown)
    at url("http://192.168.8.21:5000/webapp_tests/tests") - existing-browser.js:48:20
```

**Comment by j0tunn** [comment]
Do you still have issues with firefox and chrome?

The error you've provided is IE specific and doesn't relate to hermione. Its more about Selenium.
Take a look at [this question](https://stackoverflow.com/questions/32119931/ie11-selenium-webdriverexception-failed-to-navigate-org-openqa-selenium-webdr) on SO. It may help.
The reason usually is that IE shows some modal window on start, and this modal window blocks main window.

**Comment by mrquokka** [comment]
Now i haven't issues, i wish it helped to me, thank you!
