### ISSUE TITLE
 Error: Invalid file signature at screenshot() - existing-browser.js

### ISSUE THREAD

**Issue by tymfear** [gemini-testing/hermione#327]
Tests fails with the following error.
```
message: Invalid file signature
stack: Error: Invalid file signature at screenshot() - existing-browser.js:21:30
```

Hermione version: 0.90.2
OS: MacOS High Sierra 10.13.6 (17G65)
Node version: v8.9.1

**Comment by tymfear** [comment]
Error thrown in the `pngjs` lib in `parser.js` file, `_parseSignature` method.

**Comment by j0tunn** [comment]
Hi. Do you use git lfs?

**Comment by tymfear** [comment]
@j0tunn yeah. That causes trouble?

**Comment by tymfear** [comment]
@j0tunn thanks. That was the issue.

**Comment by j0tunn** [comment]
Yep.
