### ISSUE TITLE
Неверные пути к скриншотам в html-отчете

### ISSUE THREAD

**Issue by xhoskin** [gemini-testing/hermione#329]
Здравствуйте. 
Поднимая Гермиону на windows столкнулся с проблемой.  В отчете все слеши в путях заменяются на `%5C`. 
https://yadi.sk/i/6m9dUtYbao7eGQ

Если вручную заменить их на `/`  то картинки появляются
https://yadi.sk/i/Say1o9Uan0FFbQ

Заархивировал весь конфиг в архив:
https://yadi.sk/d/mMcBAGRb_8K77Q

**Comment by Sergey-Ubogov** [comment]
кажется это проблема html-reporter и там уже есть эта задача(https://github.com/gemini-testing/html-reporter/issues/27), но почему то зависла

**Comment by DudaGod** [comment]
Добрый вечер.
Данную проблему уже решили тут - https://github.com/gemini-testing/html-reporter/pull/316.
И оно уже доступно в версии html-reporter@5.15.3.
