### ISSUE TITLE
Ability to cleanup outdated screens

### ISSUE THREAD

**Issue by StyleT** [gemini-testing/hermione#334]
Hi!
Is there is any ability to cleanup all screenshots tests for which were removed/moved to another suite?

**Comment by unekhriukova** [comment]
In Gemini I used this approach: `find ./ -name '*size_768x1024' -exec rm -r "{}" \;`. In this case all files and folders match the '*size_768x1024' name will be deleted.

**Comment by DudaGod** [comment]
Hello.

Ability to remove unused screens is already implemented in html-reporter@8.4.2. More info about this command is here - https://github.com/gemini-testing/html-reporter#remove-unused-screens.

I close it, thank you.
