### ISSUE TITLE
Missing steps in quickstart: where to put code example and Cannot find module 'chai'

### ISSUE THREAD

**Issue by pqr** [gemini-testing/hermione#336]
I'ma trying to follow Quick Start (https://github.com/gemini-testing/hermione/blob/master/README.md#quick-start)
1) staisfied prerequisites (installed selenium)
2) installed hermione globally
3) put .hermione.conf.js in the project root
4) wrote first test: **problem 1: not clear where to write that code example?** Just guessed in 'tests/desktop', but better to put additional instructions about filename and place
5) run `hermione`: **problem 2: got an error `Error: Cannot find module 'chai'`**

**Comment by sipayRT** [comment]
hi

tnx for your feedback. Will be fixed
