### ISSUE TITLE
hermione шарит обьект browser между несколькими сессиями

### ISSUE THREAD

**Issue by vrozaev** [gemini-testing/hermione#338]
Если:
Запустить тесты в N сессиях в headless режиме 
и сохранить в beforeEach this.browser в переменную browser
то hermione шарит переменную browser в первых N сессиях. 

Воспроизведение: https://github.com/vrozaev/hermione-0.90.2-bug-reproduce

(возможно условие про headless режим лишнее, но с ним воспроизводится стабильно. Также стабильно должно воспроизводится с удаленным selenium grid)

**Comment by j0tunn** [comment]
так а проблема-то в чем?

**Comment by vrozaev** [comment]
Тесты влияют друг на друга. 

Проблемное поведение:

Тест открывает https://ya.ru, вводит в поле запроса текст `test <Номер теста>`, проверяет что был введен именно такой текст.

В ((https://github.com/vrozaev/hermione-0.90.2-bug-reproduce/blob/master/README.md логах теста)) написано:

%%
ya.ru test number 1 in file tests/test.js

chrome ✘ AssertionError: expected 'test 2test 3test 1test 4test 0' to equal 'test 1' at Object. 


ya.ru test number 2 in file tests/test.js

chrome ✘ AssertionError: expected 'test 2test 3test 1test 4test 0' to equal 'test 2' at Object. 

...
%%

Что произошло: в инпут поиска ввелся текст ##test 2test 3test 1test 4test 0##.

Ожидалось что в N разных браузерах будет введен ##test 0##, ##test 1## ##test 2##, и т.д.

**Comment by vrozaev** [comment]
@j0tunn на самом деле по этому issue уже идет работа в INFRADUTY-2632, продублировал сюда проблему так как не знал где быстрее ответят. Там ответили быстрее.
