### ISSUE TITLE
Inline svg не успевают прогрузиться

### ISSUE THREAD

**Issue by qfox** [gemini-testing/hermione#339]
Похоже, что гермиона не дожидается отображения отрисовки вставленных в html svg-элементов.

![image](https://user-images.githubusercontent.com/677518/49580420-ea206100-f95f-11e8-9c6c-6ac5ca74da62.png) ![image](https://user-images.githubusercontent.com/677518/49580579-4e432500-f960-11e8-83fc-7805b1eb244e.png)

Точно не хотим общее решение?

**Comment by sipayRT** [comment]
в большинстве случаев такое нужно стабать или игнорировать, а не ждать
Поэтому, по умолчанию такое ожидание делать нельзя. Но мы добавим базовую проверку загрузки страницы, в которой можно будет добавить кастомных условий
