### ISSUE TITLE
executionContext в ответе гермионы

### ISSUE THREAD

**Issue by hydrognomik** [gemini-testing/hermione#340]
Привет. Можно ли получить в ответе hermione объект `executionContext` для теста?

**Comment by j0tunn** [comment]
привет. Уточни в каком ответе.
Вот пример того как использовать `executionContext`: https://github.com/gemini-testing/hermione#execution-context

**Comment by hydrognomik** [comment]
Извиняюсь. Имел в виду ответ, который приходит в репортер на события, `hermione.events.TEST_FAIL`, например. Спасибо.

**Comment by j0tunn** [comment]
По сути `executionContext` - это тест, который выполняется, и который потом прилетает в `TEST_FAIL`.
Накидай, пожалуйста, больше контекста. Что ты хочешь сделать?

**Comment by hydrognomik** [comment]
Мы пытаемся пилить альтернативный репортер для гермионы и хотели добавить просмотрщик кода теста. Код теста уже есть в `executionContext.body`, вот и решили спросить как его получить в репортер.

**Comment by j0tunn** [comment]
а вот так не работает:
```js
hermione.on(hermione.events.TEST_FAIL, (test) => {
    console.log(test.body);
});
```
?

**Comment by hydrognomik** [comment]
Да, работает, спасибо большое.

**Comment by j0tunn** [comment]
@hydrognomik а расскажи, пожалуйста, что это за альтернативный репортер? Почему вы не хотите использовать https://github.com/gemini-testing/html-reporter ?
