### ISSUE TITLE
Full page screenshot с помощью Hermione

### ISSUE THREAD

**Issue by koodeex** [gemini-testing/hermione#347]
Добрый день!
Недавно начал начал интеграцию Hermione в рабочий проект и возник вопрос, на который в рамках ReadMe ответа не нашел:
Можно ли с помощью Hermione делать полностраничный скриншот в рамках прогона тестов? если да, то не могли бы Вы приложить пример того, как это можно было бы реализовать. 
Спасибо

**Comment by DudaGod** [comment]
Добрый вечер.

Можно. Нужно использовать опцию `compositeImage`.
Пример:
```js
...
browsers: {
  chrome: {
    desiredCapabilities: {...},
    compositeImage: true
  }
}
...
```

Теперь если в тесте вызвать `assertView('plain', 'body')`, то снимется скриншот всей страницы. В доке этого действительно нет. Скоро добавим.
