### ISSUE TITLE
Screenshot inside iframe

### ISSUE THREAD

**Issue by koodeex** [gemini-testing/hermione#349]
Добрый день!
Столкнулся со следующей проблемой: при переключении контекста вебдрайвера в iframe, попытка сделать assertView фотографирует левый верхний угол страницы, вне айфрейма.
можно ли как то переключить снятие скриншотов в контекст айфрейма?

 ```
it('SnapInsSupportFlowFirstPageReturn', function() { 
                return this.browser.element(iframelocator)
                .then(function (frame) {
                    return this.frame(frame.value)
                })
                .waitForVisible('#loading', 10000, true)
                .assertView('SnapInsSearchResultPageReturn', 'body');
}
```

**Comment by sipayRT** [comment]
привет

про этот баг знаем, но пока не дошли его исправить :(

**Comment by mercury-oe** [comment]
any update of this issue?

**Comment by Dino1992** [comment]
Привет! Есть новости?

**Comment by DudaGod** [comment]
Fixed in [hermione@8.2.2](https://github.com/gemini-testing/hermione/releases/tag/v8.2.2)
