### ISSUE TITLE
Проблема с исполнением тестов в IE

### ISSUE THREAD

**Issue by Amugbl4** [gemini-testing/hermione#351]
Доброго времени суток. Недавно начал осваивать ваши инструменты для тестирования вёрстки gemini и hermione. В chrome, firefox всё отлично. Столкнулся с проблемой при прогоне тестов в IE 11 на windows. IE при запуске тестов открывается, но скриншоты не делаются, никакие команды не исполняются. Тесты падают по истечение таймаута. Пробовал использовать драйвер селениума 2.47 - не помогло. Подскажите, пожалуйста в чём может быть проблема? В конфигурационном файле IE указываю как 
`  browsers: {
        ie: {
            compositeImage: true,
            desiredCapabilities: {
                browserName: 'internet explorer', 
            }
        }`
Так же буду очень признателен, если вы приведёте пример правильного указания устройств для тестирования и снятия скриншотов, iphone, ipad, например, в конфигурационном файле.

**Comment by sipayRT** [comment]
Привет

в наших проектах конфигурация для ie11 такая:

```js
    ie11: {
        compositeImage: true,
        windowSize: '1280x1024',
        desiredCapabilities: {
            browserName: 'internet explorer',
            version: '11',
            'ie.enableFullPageScreenshot': false
        },
            
    }
```

для эмуляции афйона используем такие капабилити:

```js
        desiredCapabilities: {
            browserName: 'chrome',
            version: '65.0',
            chromeOptions: {
                mobileEmulation: {
                    deviceMetrics: {
                        width: 320,
                        height: 568,
                        pixelRatio: 2.0
                    },
                    userAgent: [
                        'Mozilla/5.0',
                        '(iPhone; CPU iPhone OS 10_1_1 like Mac OS X)',
                        'AppleWebKit/602.2.14',
                        '(KHTML, like Gecko)',
                        'Version/10.0',
                        'Mobile/14B100',
                        'Safari/602.1'
                    ].join(' ')
                }
            }
        },
```

работоспособность ie11 напрямую зависит от настройки самого ie11 и iedriver-а, используемого для запуска тестов. Попробуй настроить локальный грид через https://www.npmjs.com/package/selenium-standalone

**Comment by Amugbl4** [comment]
Большое спасибо за оперативную обратную связь! Обязательно попробую описанное.

**Comment by Amugbl4** [comment]
@sipayRT Пока тикет не закрыт - воспользуюсь случаем и задам ещё один вопрос -  как можно подключить свои кастомные команды через this.browser. Возможность описана в документации, но к сожалению нет примеров, как это сделать?

**Comment by sipayRT** [comment]
это можно сделать в конфиге в [prepareBrowser](https://github.com/gemini-testing/hermione/blob/master/README.md#preparebrowser)

**Comment by Amugbl4** [comment]
@sipayRT Судя по описанию, в метод addCommand следует отправлять коллбэк. Подскажите, каким образом из этого коллбэка можно получить доступ к методам webdriverIO? Как-то через входные параметры? Просто из того, что нам удалось понять, никакие параметры на вход такого добавленного метода не поступают. Каким образом тогда можно взаимодействовать со страницей?

**Comment by Amugbl4** [comment]
Огромное спасибо, за столь быструю обратную связь! Ответы очень помогли. Если возможно не закрывать этот тикет, то было бы очень здорово, а я бы тут задавал вопросы, возникающие в процессе использования инструмента.

**Comment by j0tunn** [comment]
Лучше под новые проблемы заводить отдельные issues.
