### ISSUE TITLE
this.test is 'undefined'

### ISSUE THREAD

**Issue by evsevolodov** [gemini-testing/hermione#353]
Hi guys!
After updating hermione (from v.0.56.2 to v.1.2.1)I faced the problem that this.test in my tests is undefined. this.currentTest in beforeEach hooks works fine. 
So many of my tests broke. 
Can you help, please?

**Comment by j0tunn** [comment]
Hi. Can you provide some of your cases?

**Comment by evsevolodov** [comment]
At the screenshots below you can see results and logs of the same test in version v.0.56.2 and v.1.2.1.

<img width="894" alt="hermione_0_56_2" src="https://user-images.githubusercontent.com/8354760/50888289-6813d400-1406-11e9-9aef-bff6c380d991.png">
<img width="918" alt="hermione_1_2_1" src="https://user-images.githubusercontent.com/8354760/50888312-7235d280-1406-11e9-89aa-9d15c803f2fb.png">

**Comment by evsevolodov** [comment]
Any updates about this issue?

**Comment by j0tunn** [comment]
@evsevolodov try to use `this.currentTest` instead of `this.test` inside test callback

**Comment by j0tunn** [comment]
or you can write `flowId` directly to the context:
```js
beforeEach(function() {
    this.flowId = 'blabla';
});

it('', function() {
    this.flowId; // blabla
});

```

**Comment by evsevolodov** [comment]
Hi. This workaround works with custom variables, for example with this.flowId in beforeEach hook and this.flowId in tests.

But it looks like that **currentTest** and **test** variables (which comes from mocha) doesn't work as before. Maybe that problem related to new versions of mocha.

I'll close this issue. Thank you for your help!
