### ISSUE TITLE
Нет функций 'beforeAll' и 'afterAll' 

### ISSUE THREAD

**Issue by koodeex** [gemini-testing/hermione#357]
Добрый день! Столкнулся со следующей проблемой, требуется провести часть прекондишенов не перед каждым тестом, а один раз в начале  в рамках одного describe. В ReadME на этот счет ничего не сказано, только beforeEach и afterEach представлены. Не могли бы Вы подсказать (с примером) как это обойти или как правильно написать плагин, в которой бы передавался инстанс вебдрайвера?

**Comment by j0tunn** [comment]
В `hermione` нет before и after хуков, т.к. все тесты выполняются параллельно, и должны быть независимыми друг от друга. Соответственно `beforeEach` и `afterEach` ничем не отличаются от `before` и `after`.
https://github.com/gemini-testing/hermione#hooks

> требуется провести часть прекондишенов не перед каждым тестом, а один раз в начале в рамках одного describe

все тесты будут запущены независимо друг от друга, возможно даже в разных процессах. Поэтому прекондишены нужно выполнять в `beforeEach`

**Comment by j0tunn** [comment]
Можно в `beforeEach` выполнять проверку залогина. Если уже залогинены - ничего не делаем

**Comment by crocus-maker** [comment]
Получается что для прогона каждого сценария нужно сделать подготовку к тесту (залогин, настройки проекта етц). 
У меня эта подготовка может занимать секунд 30 и более. Для прогона теста за 2 сек

**Comment by j0tunn** [comment]
Если нужно подготовить сам сервис, то можно реализовать это в плагине на событие `RUNNER_START`: https://github.com/gemini-testing/hermione#plugins
Только браузер в этот момент еще не поднят.
Если нужно выполнить какую-то подготовку в браузере, то можно в том же плагине сделать это на событие `SESSION_START`

**Comment by seyar** [comment]
Привет. Продолжу за crocus-maker
Да, нам нужно сделать подготовку, но не на всю сессию. Аналогично по примеру выше нам нужны хуки before, after. А еще лучше уметь управлять порядком запуска тестов. 
К примеру для проверки фичи А (у нас это создание комментария в сервисе) нужно
- залогиниться
- зайти на страницу настроек выставить себе нужные права
- загрузить шаблон контракта (контракт просто некая сущность которая может содержать следующую)
- из шаблона создать контракт
- в контракт загрузить docx файл
- создать комментарий можно только на параграфе документа

Я хочу сказать о том, что наши сущности очень взаимовложены друг в друга. И перед каждым тестом так много готовить окружение не выгодно по времени.

Полагаю в данном случае нужно двигаться либо в сторону продвинутых mock ответов от нашего бекенда чтобы, пропускать шаги настроек. Либо настроить очередность выполнения тестов.

p.s. Привет, Антон :)

**Comment by seyar** [comment]
upd. Сделал с помощью ручного чтения файлов в `TestCollection` через api 
и последующей сортировкой `sortTests`

**Comment by j0tunn** [comment]
Привет.
hermione заточена под быстрый прогон тестов. Поэтому все тесты выполняются независимо друг от друга, в разных процессах, порядок не гарантируется. Более того, он не просто не гарантируется, при ретраях он точно не соблюдается, т.к. ретраи вставляются в начало очереди.
В вашем случае можно поступить так, как я предложил чуть выше: в beforeEach выполнять подготовку и выставлять какой-то флаг, который проверять при следующем выполнении beforeEach. Но работать это будет только при [workers](https://github.com/gemini-testing/hermione#workers) === 1
