### ISSUE TITLE
How to make conditional check based on visibility [docs]

### ISSUE THREAD

**Issue by Taffa** [gemini-testing/hermione#378]
How to add conditional action for example based on whether given element is visible or not?
Tried various ways with promises but getting reference error for browser

e.x.
  return this.browser
            .url('/')
             
             // How to check here if element X is visible then moveToObject('#x');
            //  If X not visible then  moveToObject('#Y');
             
            // test continues
            .click('#Something')

**Comment by j0tunn** [comment]
Take a look at [isVisible](http://v4.webdriver.io/api/state/isVisible.html)
```js
it('bla bla', async function() {
    const visible = this.browser.isVisible('#x');
    if (!visbile) {
        await this.browser.moveToObject('#Y')
    }
    // ...
});
```
