### ISSUE TITLE
страница отчета падает, если в meta в конфиге передать объект

### ISSUE THREAD

**Issue by zakaratcha** [gemini-testing/hermione#391]
![hr](https://user-images.githubusercontent.com/2573820/55077680-65da2100-50a9-11e9-82bb-71acbf156708.jpg)
Ссылка в консоли:
https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=object%20with%20keys%20%7Blogin%2C%20password%7D&args[]=

В `.hermione.conf.js`:
``` javascript
meta: {
    user: {
        login: 'testLogin',
        password: 'testpassword'
    }
}
```

Если все тесты зелёные — страница отчёта формируется нормально. Если есть упавшие тесты — вместо страницы отчёта белый лист (с `assertView` точно воспроизводится).

На странице `hermione gui` также воспроизводится.

После того, как изменил конфиг, всё заработало нормально:
```
meta: {
    userLogin: 'testLogin',
    userPassword: 'testpassword'
}
```

**Comment by sipayRT** [comment]
спасибо, посмотрим

**Comment by DudaGod** [comment]
Hello.

This problem was fixed and it is no longer reproduced.
