### ISSUE TITLE
How i can switch between windows?

### ISSUE THREAD

**Issue by CircleA** [gemini-testing/hermione#392]
Can hermione switch between browser windows ?

I've code like this, but hermione doesn't know about switchWindow method...
webdriver API contains method: https://webdriver.io/docs/api/browser/switchWindow.html
 

```
describe('test_switch_window', function (browser) {

    it('test_switch_window', function () {

        return this.browser

            .url('https://my_intresting_site.com/')

            .$("button").click() // it opens new tab

            .switchWindow("new tab's title") // output .switchWindow is not a function ;(
    });

});

```

**Comment by sipayRT** [comment]
hi

hermione use webdriverio@4.x. you should use `switchTab` command - http://v4.webdriver.io/api/window/switchTab.html
