### ISSUE TITLE
Поддержка тестов, написанных на coffescript?

### ISSUE THREAD

**Issue by Nimdim** [gemini-testing/hermione#395]
Можно-ли выполнять тесты, написанные на coffescript?
У меня удалось создать тест на JS и он работал как надо.
В той же папке я создал еще один файт с тестом, написанным на coffee.
При запуске, Hermione не выполняет coffee-файл - как будто его и нет.
Пробовал в конфигурационный файл добавить следующую настройку:
`    system: {
        mochaOpts: {
            require: "coffeescript/register",
        },
    },`
Но она не помогла - тесты на coffeescript так же не видны.
В режиме debug вижу как гермиона шлет запросы вебдрайверу, никаких ошибок нет.

**Comment by DudaGod** [comment]
Привет.

Чтобы hermione читала тесты с расширением `.coffee` тебе необходимо использовать опцию `system.fileExtensions` - https://github.com/gemini-testing/hermione#fileextensions.
А чтобы подключить компилятор `coffeescript/register` необходимо использовать cli опцию - `--require` - https://github.com/gemini-testing/hermione#require-modules.
