### ISSUE TITLE
Failed to take screenshot on reject

### ISSUE THREAD

**Issue by vitalets** [gemini-testing/hermione#399]
Привет! Хочу получать скриншот всей страницы в случае падения теста. 
Выставил значение `screenshotPath: 'failed-screenshots'`.
При запуске тестов ошибка:
```
 Failed to take screenshot on reject:     {"message":"no such window: target window already closed\nfrom unknown error: web view not found"...
```

**Comment by sipayRT** [comment]
Не смог воспроизвести поведение. Сейчас для снятия скриншота всей страницы при падении ничего делать не нужно, это делается автоматом. Но ошибка говорит о том, что на момент падения теста страница была каким-то образом поломана и невозможно было сделать ее скриншот
