### ISSUE TITLE
Настройка Proxy для Hermione

### ISSUE THREAD

**Issue by Mefistopel** [gemini-testing/hermione#406]
Здравствуйте!

Подскажите пожалуйста, как настроить Proxy в Гермионе? 
В компании применяется proxy, и обращаясь в гермионе даже к localhost - вылетает ошибка, завязанная на proxy.

**Comment by dizel3d** [comment]
Здравствуйте! Настройка прокси - это опция браузера. См. в секции [browsers](https://github.com/gemini-testing/hermione/blob/master/README.md#browsers) опцию `desiredCapabilities`. Там есть настройка `proxy`.

**Comment by Mefistopel** [comment]
Так правильно? :)

`module.exports = {
  baseUrl: 'http://localhost:4444',
  gridUrl: 'http://localhost:4444/wd/hub',
  browsers: {
      chrome: {
          desiredCapabilities: {
              browserName: 'chrome',
              proxy: {
                proxyType: 'manual',
                httpProxy: 'ip:port',
                socksUsername: 'login',
                socksPassword: 'password'
              }
          }
      },

  }
};`

**Comment by dizel3d** [comment]
@Mefistopel как я понял, это не сработало. :-) Видимо, я неправильно понял вопрос. Вы хотите в Selenium Grid через проксю ходить? В protractor для этого есть настройка [webDriverProxy](https://github.com/angular/protractor/blob/master/lib/config.ts#L110). В hermione я такой не нашел.
@sipayRT хелп

**Comment by sipayRT** [comment]
А можно подробностей накидать? как именно используется прокся, для чего она нужна для запуска тестов и т.д.
Если напрямую не получается ходить на локальные машины, то может вам просто нужен плагин [ssh-tunneler](https://github.com/gemini-testing/ssh-tunneler)?

**Comment by Mefistopel** [comment]
Извиняюсь за задержку с ответом. 
Обрисовываю ситуацию:
когда запускаю hermione в консоли папки проекта, то вылетает ошибка, завязанная на Proxy. И я не понимаю, в чём дело. Иногда успешно работает, иногда Proxy.
Помогите пожалуйста разобраться :)
```
C:\GIT\ПРОЕКТ>hermione
✘ Конвертер валют Должен появиться на странице [chrome] - 0ms
Total: 1 Passed: 0 Failed: 1 Skipped: 0 Retries: 0

1) Конвертер валют Должен появиться на странице
   in file hermione\simple.hermione.js

   chrome
     ✘ Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD><TITLE>Error Message</TITLE>
<META http-equiv=Content-Type content="text/html; charset=UTF-8">
<STYLE id=L_default_1>A {
        FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #005a80; FONT-FAMILY: tahoma
}
A:hover {
        FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #0d3372; FONT-FAMILY: tahoma
}
TD {
        FONT-SIZE: 8pt; FONT-FAMILY: tahoma
}
TD.titleBorder {
        BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 0px solid; COLOR: #955319; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left
}
TD.titleBorder_x {
        BORDER-RIGHT: #955319 0px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 1px solid; COLOR: #978c79; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left
}
.TitleDescription {
        FONT-WEIGHT: bold; FONT-SIZE: 12pt; COLOR: black; FONT-FAMILY: tahoma
}
SPAN.explain {
        FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225
}
SPAN.TryThings {
        FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225
}
.TryList {
        MARGIN-TOP: 5px; FONT-WEIGHT: normal; FONT-SIZE: 8pt; COLOR: black; FONT-FAMILY: tahoma
}
.X {
        BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; FONT-WEIGHT: normal; FONT-SIZE: 12pt; BORDER-LEFT: #955319 1px solid; COLOR: #7b3807; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: verdana; BACKGROUND-COLOR: #d1c2b4
}
.adminList {
        MARGIN-TOP: 2px
}
</STYLE>
<META content="MSHTML 6.00.2800.1170" name=GENERATOR></HEAD>
<BODY bgColor=#f3f3ed>
<TABLE cellSpacing=0 cellPadding=0 width="100%">
  <TBODY>
  <TR>
    <TD class=titleborder_x width=30>
      <TABLE height=25 cellSpacing=2 cellPadding=0 width=25 bgColor=black>
        <TBODY>
        <TR>
          <TD class=x vAlign=center align=middle>X</TD>
        </TR>
        </TBODY>
      </TABLE>
    </TD>
    <TD class=titleBorder id=L_default_2>Network Access Message:<SPAN class=TitleDescription> The page cannot be displayed</SPAN> </TD>
  </TR>
  </TBODY>
</TABLE>

<TABLE id=spacer>
  <TBODY>
  <TR>
    <TD height=10></TD></TR></TBODY></TABLE>
<TABLE width=400>
  <TBODY>
  <TR>
    <TD noWrap width=25></TD>
    <TD width=400><SPAN class=explain><ID id=L_default_3><B>Explanation:</B></ID></SPAN><ID id=L_default_4> There is a problem with the page you are trying to reach and it cannot be displayed. </ID><BR><BR>
    <B><SPAN class=tryThings><ID id=L_default_5><B>Try the following:</B></ID></SPAN></B>
      <UL class=TryList>
        <LI id=L_default_6><B>Refresh page:</B> Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion.
<LI id=L_default_7><B>Check spelling:</B> Check that you typed the Web page address correctly. The address may have been mistyped.
<LI id=L_default_8><B>Access from a link:</B> If there is a link to the page you are looking for, try accessing the page from that link.

      </UL>
<ID id=L_default_9>If you are still not able to view the requested page, try contacting your administrator or Helpdesk.</ID> <BR><BR>
    </TD>
  </TR>
  </TBODY>
</TABLE>

<TABLE id=spacer><TBODY><TR><TD height=15></TD></TR></TBODY></TABLE>

<TABLE width=400>
  <TBODY>
  <TR>
    <TD noWrap width=25></TD>
    <TD width=400 id=L_default_10><B>Technical Information (for support personnel)</B>
      <UL class=adminList>
        <LI id=L_default_11>Error Code: 502 Proxy Error. The ISA Server denied the specified Uniform Resource Locator (URL). (12202)
<LI id=L_default_12>IP Address: PROXY ADRES (причение автора)
<LI id=L_default_13>Date: 5/22/2019 7:09:13 AM [GMT]
<LI id=L_default_14>Server: SERVER ADRES (причение автора)
<LI id=L_default_15>Source: proxy

      </UL>
    </TD>
  </TR>
  </TBODY>
</TABLE>

</BODY>
</HTML>


    at new RuntimeError (C:\Users\UserName\node_modules\@gemini-testing\webdriverio\build\lib\utils\ErrorHandler.js:143:12)
    at Request._callback (C:\Users\UserName\node_modules\@gemini-testing\webdriverio\build\lib\utils\RequestHandler.js:302:39)
    at Request.self.callback (C:\Users\UserName\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (C:\Users\UserName\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (C:\Users\UserName\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Когда ту же команду запускаю через VSCode всё корректно отрабатывает, хотя иногда и нет
```
chrome
     ✘ Error: ESOCKETTIMEDOUT (ESOCKETTIMEDOUT)
```
Успешно: 
```
PS C:\GIT\ПРОЕКТ> hermione
✘ Конвертер валют Должен появиться на странице [chrome:9c430bd0c9909265a2df42768b9b56a4] - 2370ms
Total: 1 Passed: 0 Failed: 1 Skipped: 0 Retries: 0

1) Конвертер валют Должен появиться на странице
   in file hermione\simple.hermione.js

   chrome
     ✘ AssertionError [ERR_ASSERTION]: Конвертер валют не поя22вился
    at Object.browser.url.isExisting.then (C:\GIT\webscada\WebScada.Client\hermione\simple.hermione.js:9:14)
    at Object.exec (C:\Users\UserName\node_modules\@gemini-testing\webdriverio\build\lib\helpers\safeExecute.js:28:24)
    at Object.resolve (C:\Users\UserName\node_modules\@gemini-testing\webdriverio\build\lib\webdriverio.js:194:29)
    at C:\Users\UserName\node_modules\@gemini-testing\webdriverio\build\lib\webdriverio.js:533:32
    at _fulfilled (C:\Users\UserName\node_modules\@gemini-testing\webdriverio\node_modules\q\q.js:854:54)
    at C:\Users\UserName\node_modules\@gemini-testing\webdriverio\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\UserName\node_modules\@gemini-testing\webdriverio\node_modules\q\q.js:816:13)
    at C:\Users\UserName\node_modules\@gemini-testing\webdriverio\node_modules\q\q.js:624:44
    at runSingle (C:\Users\UserName\node_modules\@gemini-testing\webdriverio\node_modules\q\q.js:137:13)
    at flush (C:\Users\UserName\node_modules\@gemini-testing\webdriverio\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Исходные данные:
- selenium-standalone start (глобальный)
- файл .hermione.conf.js в корне проекта (hermiona установлена в корень через npm)
```
module.exports = {
  gridUrl: 'http://localhost:4444/wd/hub',

  browsers: {
      chrome: {
          desiredCapabilities: {
              browserName: 'chrome'
          }
      },
  }
};
```
- файл с тестовым сценарием simple.hermione.js
```
const assert = require('assert');

describe('Конвертер валют', () => {
  it ('Должен появиться на странице', function() {
    return this.browser
    .url('http://localhost:4444')
    .isExisting("div[class='q-stepper-header row items-stretch justify-between shadow-1']")
    .then((exists) => {
      assert.ok(exists, 'Конвертер валют не появился');
    });
  });
});

```

**Comment by sipayRT** [comment]
а зачем ты ходишь за страницей для теста на порт селениума?
```
.url('http://localhost:4444')
```
> Иногда успешно работает, иногда Proxy.

не мог он у тебя успешно работать - ты ходишь в грид и пытаешься там выполнить свой тест. То, что в какой-то момент ты получил ошибку `Конвертер валют не поя22вился`, как раз и означает, что на этой странице ничего похожего нет. Тебе в тесте нужно открывать страницу, которую ты хочешь тестировать (я подозреваю, что у тебя это 'http://localhost:8080')

**Comment by Mefistopel** [comment]
Я заходил для проверки. У меня по этом адресу выводится страница о Селениуме и я писал тестовый скрипт для проверки отображения элементов.
Даже сейчас, когда я проверяю на localhost:5000 (там WEB-приложение), в cmd выводит ошибку, html которой я написал выше.

**Comment by sipayRT** [comment]
> вопрос: на основе https://webdriver.io/docs/api/element/addValue.html как в input элемент с классом login можно ввести данные?

`this.browser.setValue('.login', 'test')`? В доке wdio все описано с примерами. Только тебе лучше смотреть в доке версии v4 - http://v4.webdriver.io/api/action/addValue.html

**Comment by Mefistopel** [comment]
За ссылку на док v4 -> **большое спасибо!**

А вот с proxy вопрос ещё висит. Я реально не понимаю в чём дело.
Вчера, когда вопрос задавал, в VSCode и cmd вылетала такая же ошибка с прокси. А из cmd потом гермиона начала запускаться (каким-то чудом).

Наблюдения: при запуске из cmd даже не открывается браузер селениума, просто вылетает ошибка в html.

**Comment by sipayRT** [comment]
Если у тебя даже не открылся браузер со страницей, то откуда он взял html этой страницы? Я все еще не понимаю при чем здесь прокси вообще - без этой доп.настройки все запускается нормально?

Самый правильный путь - это сначала сделать минимальную рабочую конфигурацию, чтобы тест у тебя запускался и успешно проходил. А после этого уже пробовать добавлять логики

**Comment by Mefistopel** [comment]
Судя по проведённым экспериментам, я так понимаю, что hermiona получает этот html при обращении к selenium по gridUrl: 'http://localhost:4444/wd/hub'.

**Comment by Mefistopel** [comment]
Закрываю топик: проблема произошла при установке селеинума. До сих пор не понимаю, что произошло при установке, но при cmd -> **selenium-standalone start** в cmd не выводится последняя строчка. 

> Selenium started


Решил проблему так (топорно, но работает): на другом ПК установил и запустил селениум и гермиона обращается к его ip в .hermione.config.js 

> gridUrl: 'http://    ip   :4444/wd/hub'

**Кто найдёт нормальное решение данной проблемы, напишите, пожалуйста, на почту jdkz@yandex.ru** 

### Кому нужна инструкция по установке Hermine для Windows 
1.	Установить NodeJS и npm https://nodejs.org/en/ (v.10xx) 
2.	Установить Python v2 https://www.python.org/downloads/
3.	Установить Java https://www.java.com/ru/
4.	Установить Java SE Development Kit https://www.oracle.com/technetwork/java/javase/downloads/index.html
5.	Установить git (любое приложение) https://gitforwindows.org
6.	Установить Visual Studio 201(_версия_) https://visualstudio.microsoft.com/ru/vs/whatsnew/
7.	Установить Visual C++ Build Tools https://www.microsoft.com/ru-ru/download/confirmation.aspx?id=48159
8.	Перезагружаем ПК
9.	Запускаем cmd под правами администратора
10.	Выполнить следующие команды:
10.1.	npm install -g node-gyp
10.2.	npm config set msvs_version 201(_версия_) –global
10.3.	npm install --global --production windows-build-tools
10.4.	npm install -g webdriverio
10.5.	npm i -g vvo/selenium-standalone
10.6.	selenium-standalone install
10.7.	npm i -g hermione
10.8.	npm init --yes
10.9.	npm i -save chai
10.10.	selenium-standalone start (сервер selenium будет запущен и доступен по следующему адресу http://localhost:4444)
 
11.	 В проекте создать файл .hermione.conf.js со следующим содержимым:
```
module.exports = {
  baseUrl: 'http://localhost:4444', //куда будет обращение с selenium
  gridUrl: 'http://localhost:4444/wd/hub' //обращение к серверу selenium,
  browsers: {
      chrome: {
          desiredCapabilities: {
              browserName: 'chrome'
          }
      },
  }
};
```

12.	 В проекте создать попку hermione
13.	 В папке hermione создать тестовый сценарий test.hermione.js cо следующим содержимым:
```
const assert = require('assert');
describe('Первый скрипт, () => {
  it ('Загрузка мастера', function() {
    return this.browser
    .url('/')
    .getUrl()
    .then((url) => {
      assert.ok(url == 'http://localhost:4444, 'Мастер не появился');
    });
  });
});
```
14.Открыть новую cmd, перейти в папку, где лежит файл .hermione.config.js 
15.	 Выполнить команду hermione
Запустится автоматизированное тестирование.
