### ISSUE TITLE
Общие вопросы по написанию тестов

### ISSUE THREAD

**Issue by Mefistopel** [gemini-testing/hermione#407]
Предложение: может вам создать чат, где пользователи могут задавать вопросы по написанию тестовых сценариев с помощью гермионы?

Например, как можно написать тестовый сценарий в гермионе аналогично нижеприведённому? Так как при исполнении скрипта ругается на browser, getText и т.д.

```
it('should wait until text has changed', function () {
    browser.waitUntil(function () {
      return browser.getText('#someText') === 'I am now different'
    }, 5000, 'expected text to be different after 5s');
});
```
Интересует именно внутреннее обращение к элементам внутри функций webdriver.

**Comment by j0tunn** [comment]
> Предложение: может вам создать чат, где пользователи могут задавать вопросы по написанию тестовых сценариев с помощью гермионы?

У нас нет возможности круглосуточной поддержки пользователей. 

> Так как при исполнении скрипта ругается на browser, getText и т.д.

В теле теста к браузеру нужно обращаться через `this.browser`
Внутри waitUntil можно обратиться через `this` - это уже чистый webdriverio. Либо можно сделать функцию стрелочной, и сходить через `this.browser`

**Comment by Mefistopel** [comment]
При применении кода
```
.waitUntil(  () => this.browser.getText('.text') === 'localhost\\SQLExpress'
    , 5000, 'Значение Input Database Server Name пусто')
```

вылетает ошибка
```
chrome
     ✘ Error: Promise was rejected with the following reason: undefined
    at elements(".text") (C:\Users\userName\AppData\Roaming\npm\node_modules\hermione\node_modules\@gemini-testing\webdriverio\build\lib\commands\getText.js:18:17)
    at getText(".text") (C:\GIT\project\component.project\tests\hermione\setup.hermione.js:30:37)
    at waitUntil(<Function>, 5000, "Значение Input Database Server Name пусто") (C:\GIT\project\component.projec\tests\hermione\setup.hermione.js:30:6)
```

Пробовал и через function с `this`, и в фигурных скобках и т.д. Подскажите пожалуйста, в чём проблема.

**Comment by Mefistopel** [comment]
+ вопрос: можно ли отключить запуск браузеров в селениуме для ускоренного тестирования?

Сейчас, при отправке тестов на hermione селениум открывает нужный браузер и выполняет действия там. Можно ли это сделать без открытия браузера? И ускорит ли это выполнение тестов?

+ можете поделиться стратегией тестирования, которую вы применяете для тестирования WEB-приложений: организация папок, файлов тестов.  
+ Как отключать ненужные тесты в папке без их переноса или переименования? 
+ Как можно подключить в test.hermione.js файл с переменными - селекторами элементов, чтобы не дублировать код отдельных файлах?

**Comment by j0tunn** [comment]
> вылетает ошибка

судя по стэктрейсу команда `getText` выполняется. Но сказать что-то конкретное сложно, нужно дебажить. Судя по первому сниппету с кодом не возвращается промис и коллбэка теста, нужно делать либо `return this.browser...` либо `await this.browser...`. Есть вероятность, что ошибка может быть в этом, т.к. `getText` в таком случае будет выполняться тогда, когда сессия браузера закрывается или уже закрыта

> вопрос: можно ли отключить запуск браузеров в селениуме для ускоренного тестирования?

можно запускать в chrome в режиме `headless`: https://peter.sh/experiments/chromium-command-line-switches/#headless
аргументы передаются в `desiredCapabilities` через опцию `chromeOptions -> args`: http://chromedriver.chromium.org/capabilities

> можете поделиться стратегией тестирования, которую вы применяете для тестирования WEB-приложений: организация папок, файлов тестов.

файлы с тестами кладем рядом с исходниками, добавляя суффикс `hermione.js`, потом просто по маске подключаем в конфиге

> Как отключать ненужные тесты в папке без их переноса или переименования?

можно отключить в коде тестов через `skip` или `only`: https://github.com/gemini-testing/hermione#skip

> Как можно подключить в test.hermione.js файл с переменными - селекторами элементов, чтобы не дублировать код отдельных файлах?

обычным `require`

> Как можно отобразить то, что, например, получает .getText(selector)?

через `console.log`

Вообще многие из вопрос не имеют отношения непосредственно `hermione`, рекомендую также ознакомиться с документацией `webdriverio`: http://v4.webdriver.io (обращаю внимание на то, что в hermione используется 4я версия)

**Comment by Mefistopel** [comment]
### Спасибо за ответы на вопросы! Они мне очень помогли!)

Да, я понимаю, что многие вопросы относятся к самому webdriver, но я просто хочу максимально быстро и эффективно получить знания от специалистов, а не тратить впустую время в поисках нужной информации на просторах интернета.
С гермионой и системой автоматического тестирования (selenium + webdriver) я столкнулся впервые, поэтому стараюсь получить знания обо всём этом от вас. Прошу прощения за возможную наглость. :)

Если посоветуете курсы/литературу/ресурсы, чтобы они покрыли все возможные предстоящие вопросы, прошу написать. И, да, с документацией гермионы ознакомлюсь более внимательно.

**Comment by Mefistopel** [comment]
Подскажите пожалуйста, как можно проверить исчезновение элемента со страницы? Мол, ожидать какое-то время, пока элемент не исчезнет.
Что-нибудь обратное функции `.waitForVisible()`, которая ждёт появление элемента.

**Comment by DudaGod** [comment]
У метода `waitForVisible()` есть 3ий аргумент - `reverse`. Если в него передать `true`, то  он будет ожидать пока элемент не исчезнет. Дока про метод `waitForVisible` - http://v4.webdriver.io/api/utility/waitForVisible.html.

Про гермиону можешь посмотреть вот этот доклад - https://www.youtube.com/watch?v=MbDmkq0QT-I

**Comment by Mefistopel** [comment]
Вопрос: как можно вывести общее время выполнения всех тестов?

Пробовал через (см ниже), но не видит функцию `performance.now()`
```
var t_start = 0, t_end = 0;
  
  hermione.on(hermione.events.RUNNER_START, () => {
    t_start = performance.now();
  });

  hermione.on(hermione.events.NEW_BROWSER, () => {
      // outputs `false`, because `NEW_BROWSER` event was triggered in a subprocess,
      // but `RUNNER_START` was not
     
  });

  hermione.on(hermione.events.RUNNER_END, () => {
      // outputs `true`
      t_end = performance.now();
      console.log((t_end - t_start).toFixed(4));
  });
```


Также вопрос по` hermione.intercept` -> `return {event: hermione.events.SUITE_END};` завершает только тесты, объявленные в `describe`, но а если тест поломан и дальнейшее выполнение тестов не имеет смысла, то что можно вернуть при 
`hermione.intercept(hermione.events.TEST_FAIL, ({event, data}) => {
...
}`?

**Comment by Mefistopel** [comment]
Дополнительный вопрос: как можно подключить самонаписанный плагин для гермионы из нужной папки, а не **node_modules**? Фишка в том, что необходимо пушить изменения custom_plagins в гит, но папка node_modules в **gitingnore**. Это жутко неудобно. 
```
plugins: {
    //если гермиона установлена глобально, папку с плагинами закидывать в путь
    //C:\Users\nameUser\AppData\Roaming\npm\node_modules\hermione\node_modules

    //если локально C:\GIT\project\node_modules
    'hermione-custom-plugins-webscada' : true
  },
```

Было бы замечательно, если бы можно было указывать путь типа такого:
```
plugins: {
    'src/tests/hermione-custom-plugins-webscada' : true
  },
```

**Comment by sipayRT** [comment]
можешь хранить их в своей папке, а в package.json эту зависимость можно указать как 

```js
"my-plugin": "file:tests/plugins/my-plugin"
```

**Comment by Mefistopel** [comment]
Подскажите пожалуйста, почему в функции` .then` не работают` .split() `и `slice()` ? Как их можно вызвать в кастомной команде для гермионы?
 ```
 .getText(elementInput.text)
        .then(function(text) {
           messageElementSplit = text.split('"')[0]
           messageLength = messageElementSplit.length
           messageSlice = message.slice(0, messageLength)
           console.log(`
           ${messageElementSplit} ${messageSlice} ${messageLength}
           ${messageElementSplit == messageSlice}
           `)
           assert.ok(messageElementSplit == messageSlice, 'Не отобразилось сообщение: '+ message)
        })
```

Полная команда:
```
browser.addCommand('testMessageNotify', (button, elementInput, message) => {
      return browser
        .isVisible(elementInput.element)
        .then((status) => {
            if (status) {
              return browser
               .waitForVisible(elementInput.element, 30000, true)
          }
        })
        .click(button)
        .waitForVisible(elementInput.element, 30000)
        .getText(elementInput.text)
        .then(function(text) {
           messageElementSplit = text.split('"')[0]
           messageLength = messageElementSplit.length
           messageSlice = message.slice(0, messageLength)
           console.log(`
           ${messageElementSplit} ${messageSlice} ${messageLength}
           ${messageElementSplit == messageSlice}
           `)
           assert.ok(messageElementSplit == messageSlice, 'Не отобразилось сообщение: '+ message)
        })
    })
```

**Comment by Mefistopel** [comment]
1) Вопрос по замеру времени выполнения всех тестов (от начала и до конца) остаётся актуальным :)
2) И вопрос: если какой-нибудь из `it()` сломался в `describe1`, то выполнение тестов в  `describe1` завершается  переходит к следующему `describe2`

**Comment by j0tunn** [comment]
> Пробовал через (см ниже), но не видит функцию performance.now()

В node нет performance.now(). Исползьуй либо сторонний модуль, либо Date, либо console.time

> И вопрос: если какой-нибудь из it() сломался в describe1, то выполнение тестов в describe1 завершается переходит к следующему describe2

В hermione минимальная неделимая единица - это тест. Так что нет, другие тесты из `describe1` тоже выполнятся. Более того, последовательность выполнения тестов в одном `describe` не гарантируется.

**Comment by sipayRT** [comment]
Для замера времени можно использовать плагин [stat-reporter](https://github.com/gemini-testing/stat-reporter). В результате ты получишь табличку вида

![image](https://user-images.githubusercontent.com/1658415/59746098-ce870300-927e-11e9-98f8-3901f6dd0273.png)

**Comment by Mefistopel** [comment]
Как можно запустить один и тот же тест, но при разных переменных?
Для приложения происходит проверка локализации, поэтому выполняются одни и те же действия. Лишь переменные подставлять в зависимости от прохождения.

Пробовал решить проблему через промисы и async/await. Не получилось.
Пример:
```
switch(number) {
  case 1:  
    language.text = 'en_us'
    language.element = variables.scada._11_profile.card_language.select.language.en_us
    language.message = variablesMessage.en_us
    break;

  default:
    language.text = 'ru'
    language.element = variables.scada._11_profile.card_language.select.language.ru
    language.message = variablesMessage.ru
    break;
}
describe('Проверка языка '+language.text, () => {
  it ('Проверка локализации 1', function(){
    return this.browser
      .testLanguage(language.element, language.message) //берём из селектора lenguage.elemnt текст и проверяем с текстом, language.message
  })
  it ('действие 2', function(){
    //код...
  }) 
})
```

Пробовал всё в функцию сделать: 
```
function testLanguage(number){
  switch(number) {
    case 1:  
      language.text = 'en_us'
      language.element = variables.scada._11_profile.card_language.select.language.en_us
      language.message = variablesMessage.en_us
      break;
  
    default:
      language.text = 'ru'
      language.element = variables.scada._11_profile.card_language.select.language.ru
      language.message = variablesMessage.ru
      break;
  }
  describe('Проверка языка '+language.text, () => {
    it ('Проверка локализации 1', function(){
      return this.browser
        .testLanguage(language.element, language.message) //берём из селектора lenguage.elemnt текст и проверяем с текстом, language.message
    })
    it ('действие 2', function(){
      //код...
    }) 
  })
}
```

Потом сделать её асинхронной с промисами:
```
function testLanguage(number, resolve){
...

  describe('Проверка языка '+language.text, () => {
    it ('Проверка локализации 1', function(){
      //код..
    })
    it ('действие 2', function(){
      //код...
    }) 
   resolve()
  })
}
function delay1() {
  return new Promise(resolve => testLanguage(1, resolve));
}
function delay2() {
  return new Promise(resolve => testLanguage(2, resolve));
}
```
И так далее. Помогите пожалуйста) Либо, получается, что надо дублировать по 100+ однотипного кода?

**Comment by j0tunn** [comment]
Асинхронным может быть только код тестов. Соответственно выглядеть это должно как-то так:
```js
function testLanguage({language, element, message}) {
    describe(`проверка языка ${language}`, () => {
        it('проверка локализации 1', function() {
            return this.browser
                // код взаимодействия с браузером
        });
        
        it('проверка локализации 2', function() {
             return this.browser
                // код взаимодействия с браузером
        });
    });
}

testLanguage({language: 'ru', element: ...});
testLanguage(...);
```

**Comment by Mefistopel** [comment]
> можешь хранить их в своей папке, а в package.json эту зависимость можно указать как
> 
> ```js
> "my-plugin": "file:tests/plugins/my-plugin"
> ```

Добавлю для разбирающихся, что можно установить свой отдельный плагин через команду `npm`:
`npm install ./tests/plugins/hermione-custom-plugins --save`
и добавятся зависимости в 
1) package-lock.json:
```
 "dependencies": {
//...другие пакеты
     "hermione-custom-plugins-webscada": {
          "version": "file:tests/plugins/hermione-custom-plugins"
     }
}
```
2) package.json
```
"dependencies": {
    "hermione": "^2.7.1",
    "hermione-custom-plugins-webscada": "file:tests/plugins/hermione-custom-plugins"
  }
```

**Comment by Mefistopel** [comment]
Вопрос по **webdriver**: как можно реализовать перемещение элемента на странице с помощью зажатого левой кнопки мыши?

Мол, можем менять элементы местами с помощью указателя мыши.

**Comment by Mefistopel** [comment]
Подскажите пожалуйста, можно ли как-то создать массив с ошибками, чтобы под конец теста он выводился?
Чтобы не применять `assert.ok()`, который останавливает выполнение тестов в `it()`. Если гермиона находит ошибку, то она её записывает в массив и по завершению выполнения всех тестов выводит в консоль.
Иначе говоря, нужно, чтобы сценарий выполнения тестов не прерывался во время нахождения ошибки.

Пытался реализовать через кастомную команду, которая пушит новый элемент в массив **massError** , но массив не изменяется.
```
module.exports = (hermione, opts) => {
  var t_start = 0, t_end = 0;
  var massError = []; //массив ошибок
  
  hermione.on(hermione.events.RUNNER_START, () => {
    t_start = Date.now();
  });

  hermione.on(hermione.events.RUNNER_END, () => {
      // outputs `true`
      t_end = Date.now();
      let time_test = (t_end - t_start)/1000;
      console.info(`
      
      ВРЕМЯ ВЫПОЛНЕНИЯ ТЕСТОВ:  
        ${(time_test/60).toFixed(2)}  МИНУТ
        ${time_test}  СЕКУНД

        ${massError.length}
      `);
  });

browser.addCommand('testLanguage', (elementInput, message, variable) => {
      return browser
        .waitForText(elementInput, 1500)
        .getText(elementInput)
        .then((textGet) => {
          if (message.toLowerCase() != textGet.toLowerCase()) {
            massError.push(
              `${massError.length}
                Переменная -> ${variable} 
                Не отобразилась локализация ->  ${messageServer}
                Отображено -> ${textOnBrowser}`
            )
          }
    })
```

**Comment by j0tunn** [comment]
тесты (и в частности новая команда `testLanguage`) выполняются в воркерах , а `RUNNER_END` летит на уровне мастер-процесса.
Можно использовать `hermioneCtx` для трансфера данных между воркерами и мастером:
- в воркере пишем в `browser.executionContext.hermioneCtx`
- в мастере читаем из поля `hermioneCtx`, которое летит в данных на события от тестов

**Comment by Mefistopel** [comment]
А можно пример?

Я сделал так и переменная в ctx не изменяется :
файл .hermione.conf.js

```
system: {
    ctx: {
      foo: 1
    }
}
```
в файле теста:
```
it('awesome test', function() {
      return this.browser
        .then(()=>{
          console.log(hermione.ctx.foo)
          hermione.ctx.foo+=1;
          console.log(hermione.ctx.foo) //переменная изменилась
        })
    });
```


в файле своего плагина **index.js**:
```
hermione.on(hermione.events.RUNNER_END, () => {
      console.log(hermione._config.system.ctx.foo) //после выполнения теста выводится то, что прописано в hermione.conf.js
  });
```

**Comment by j0tunn** [comment]
я говорю не о конфиге.
в файле теста в воркере пишем в `browser.executionContext.hermioneCtx`
```
it('awesome test', function() {
      return this.browser
        .then(()=>{
          this.executionContext.hermioneCtx.foo = 'bar';
        })
    });
```

в файле своего плагина **index.js**:
```
module.exports = (hermione, opts) => {
    hermione.on(hermione.events.TEST_END, (test) => {
         console.log(test.hermioneCtx);
    });
}
```

**Comment by Mefistopel** [comment]
Вопрос по WebDriver: при работе с web-приложением есть кнопка загрузки файла на сайт, по которой кликаем и появляется окно выбора файла 
![image](https://user-images.githubusercontent.com/16778030/61679725-5c985280-ad31-11e9-966f-534fdfe7ec74.png)


Как с помощью Гермионы можно работать с окном? И выбрать определённый файл?

**Comment by j0tunn** [comment]
Никак нельзя. Это уже не браузер, это системное окно.
Максимум можно глянуть на вот эту статью: https://webdriver.io/blog/2019/06/25/file-upload.html

**Comment by Mefistopel** [comment]
Можно пожалуйста пример кода, когда необходимо пройтись по вложенным элементам div-элемента и выполнить какое-либо действие с нужным значением.

Мол, в этой структуре необходимо найти XPath-адрес элемента "**Четвёртый**"
```
<div>
    <div> Первый </div>
    <div> Второй </div>
    <div> Третий </div>
    <div> **Четвёртый** </div>
    <div> Пятый </div>
</div>
```



Например (наверняка не рабочая функция, хотя не проверял):
```
findElement(elementDOM, tag,  valueText) {
    let findNumberElement = 1;
    let findReturnElement = `${elementDOM}/${tag}[${findNumberElement}]`; //XPath
    
    while (true) { //повторять до тех пор, пока не найден элемент с нужным содержимым
      return this.browser
        .getText(findReturnElement)
        .then((textGet) => {
          if (textGet == valueText || findNumberElement > 100) break;
          findNumberElement += 1;
        })
    }
    return findReturnElement //вернуть нужный XPath-элемент
  }
```

**Comment by j0tunn** [comment]
Я не понял вопроса. Достаточно просто указать правильный селектор при вызове метода действия. К hermione и даже к webdriverio отношения не имеет вообще. Имеет смысл в первую очередь пользоваться поиском по интернету. Скорее всего речь идет о [nth-child](https://developer.mozilla.org/ru/docs/Web/CSS/:nth-child)

Функция точно не рабочая, там в `while` вызывается `return`, что приведет к выходу из функции на первой же итерации

**Comment by Mefistopel** [comment]
У меня загвоздка в том, что web-приложение динамическое: пользователь может создавать динамические страницы с любым названием, которые отображаются в меню слева и происходит сортировка по алфавиту.

Поэтому я хочу искать среди множества div элементов нужный мне по какому-либо свойству.
Получается, необходимо:
1) Подсчитать количество элементов в div
2) Найти нужный

**Comment by j0tunn** [comment]
сделай это js'ом на странице через `execute`. А дальше либо возвращаешь в тест номер, и из него уже формируешь правильный селектор. Либо прямо на месте `js`'ом и выполняешь нужное действие.

**Comment by HamsterCoder** [comment]
@Mefistopel добавляйся в чат - пользователи помогут пользователям https://t.me/hemione_testing_self_support

**Comment by Mefistopel** [comment]
При выполнении тестов в Гермионе в консоли отображается запись:

> (You can disable this warning by setting `"deprecationWarnings": false` in your WebdriverIO config)
> WARNING: the "moveTo" command will be deprecated soon. If you have further questions, reach out in the WebdriverIO Gitter support channel (https://gitter.im/webdriverio/webdriverio).
> Note: This command is not part of the W3C WebDriver spec and won't be supported in future versions of the driver. It is recommended to use the actions command to emulate pointer events.

Подскажите пожалуйста, как можно отключить отображение данной записи через Гермиону?)

**Comment by j0tunn** [comment]
> Подскажите пожалуйста, как можно отключить отображение данной записи через Гермиону?)

Никак. Нет такой возможности, это нужно добавлять вот сюда: https://github.com/gemini-testing/hermione/blob/master/lib/browser/browser.js#L43

**Comment by shdenhome** [comment]
Привет! Подскажите пожалуйста. Настроил пайплайн, тесты выполняются в контейнере. При локальном создании эталонов и последующим запуском все норм. При выполнении с той же конфигурацией в контейнере, возникает ошибка `image comparison failed`. Подскажите, как быть? Подразумеваю что эталонные изображения не находит (при выполнении в контейнере).

**Comment by j0tunn** [comment]
Нужно положить эталоны в контейнер так же, как положили тесты

**Comment by shdenhome** [comment]
> Нужно положить эталоны в контейнер так же, как положили тесты

Так они там есть, но, при каждом запуске фреймворк ищет в другой папке ( типа 0c7e8a8 ). Получается мне нужно в контейнере сделать эталоны и потом уже с ними запускать тесты. Я же хочу эталоны делать локально.

**Comment by j0tunn** [comment]
К сожалению без подробностей схемы запуска, без конфига и без логов запуска могу только гадать. hermione ищет скриншоты в папке, соответствующей фуллтайтлу теста (это буквально хэш от фуллтайтла), и если при каждом запуске поиск идет в другой папке, то это значит, что меняется имя теста

**Comment by shdenhome** [comment]
**j0tunn** спасибо, все получилось. Оказалось банально, гит не подхватил эталоны)

**Comment by coustoue** [comment]
Здравствуйте, 
при попытке выполнить последний тест (код ниже) 
вылетает ошибка
```
 ✘ TypeError: Cannot read property 'hermioneCtx' of undefined
    at TestRunner.run (C:\DATA\App\hermione\node_modules\hermione\lib\worker\runner\test-runner\index.js:29:34)        
    at Runner.runTest (C:\DATA\App\hermione\node_modules\hermione\lib\worker\runner\index.js:37:23)
    at Hermione.runTest (C:\DATA\App\hermione\node_modules\hermione\lib\worker\hermione.js:31:29)
    at syncConfig.then (C:\DATA\App\hermione\node_modules\hermione\lib\worker\hermione-facade.js:40:40)
    at tryCatcher (C:\DATA\App\hermione\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\DATA\App\hermione\node_modules\bluebird\js\release\promise.js:547:31)     
    at Promise._settlePromise (C:\DATA\App\hermione\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\DATA\App\hermione\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\DATA\App\hermione\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\DATA\App\hermione\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\DATA\App\hermione\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues (C:\DATA\App\hermione\node_modules\bluebird\js\release\async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)

```
Код:
```
const assert = require('assert')
const desireUrl='https://mail.ru/'
const selector = '#q'

function openPage(url) {
  it ('openPage - ' + url, function() {
    let msg = 'Wrong page: '
    return this.browser
      .url(url)
      .getUrl()
        .then((getUrl) => {
        if (url!==getUrl) assert.fail(msg + getUrl)
      })
  })
}

function setInput(selector, text) {
  it ('setInput - selector: ' + selector + (text.length > 0 ? ': ' + text : ''), function (){
    if (text===undefined) text='undefined'
    let msg = 'Text mismatch - '
    return this.browser
      .waitForVisible(selector, 5000)
      .setValue(selector, text)
      .getValue(selector)
        .then((value) => {
          if (!value===text) { assert.fail(msg + text + ':' + value) }
        })
  })
}

function randomString(length=4) {
  if (isNaN(length)) return ''
    else if (length < 0) return ''
    let rnd = ''
    while (rnd.length < length) rnd += Math.random().toString(36).substring(2)
    return rnd.substring(0, length)
  }

// hermione.skip.in('chrome', "It shouldn't work this way in Chrome")
describe('Mail.ru - const string', () => {
  openPage(desireUrl)
  let str =  'textg7l6'
  setInput(selector, str)
  console.log('typeof: ', typeof str, str)
})

// hermione.skip.in('chrome', "It shouldn't work this way in Chrome")
describe('Mail.ru - Math.random()', () => {
  openPage(desireUrl)
  let str =  Math.random()
  setInput(selector, str)
  console.log('typeof: ', typeof str, str)
})

// hermione.skip.in('chrome', "It shouldn't work this way in Chrome")
describe('Mail.ru - randomString()', () => {
  openPage(desireUrl)
  let str =  randomString()
  setInput(selector, str)
  console.log('typeof: ', typeof str, str)
})
```

в консоль выводятся следующие данные:
```
typeof:  string textg7l6
typeof:  number 0.09451411534056042
typeof:  string be95
```
непонятно где "криминал"?
