### ISSUE TITLE
Некорректная работа `ignoreElements` в compositeImage

### ISSUE THREAD

**Issue by Ingewar** [gemini-testing/hermione#408]
При включенной опции compositeImageб `ignoreElements` срабатывает только один раз, для первого скриншота. В остальных же скриншотах это не работает и получаеться так, что если элемент попадает на склейку, то первая его часть закрашена, а вторая нет. 
Кейс данный кейс случается с различными эмбедами, которые нужно игнорировать, но нельзя просто поставить display=none.

**Comment by ulitcos** [comment]
Привет, столкнулся с такой же проблемой. Смог закостылить при помощи [execute](https://webdriver.io/docs/api/browser/execute.html). Получился примерно такой код:
```
it(name, function() {
    return this.browser
        .url(`https://${yourUrl}`)
        .execute(() => {
            const problematicElement = document.querySelector('.problematicElement');
            problematicElement && problematicElement.remove();
        })
        .assertView(name, 'body')
});
```
вместо `remove` можно использовать `opacity: 0` или `display: none`

**Comment by sipayRT** [comment]
Проверил, что с версии hermione@5.6.2 данный баг не воспроизводится - элементы закрашиваются корректно на всём склеенном скриншоте. В качестве пруфа добавил в игнор иконки сайтов на выдаче яндекса:
![image](https://user-images.githubusercontent.com/1658415/225311559-cf3d4395-5c62-44a3-9e74-0c6856811c01.png)
