### ISSUE TITLE
Hermione запускается, но тесты как будто не видит

### ISSUE THREAD

**Issue by shishkin17** [gemini-testing/hermione#409]
После запуска тестов выводит везде нули:

Total: 0 Passed: 0 Failed: 0 Skipped: 0 Retries: 0

Ниже указан конфиг

**package.json:**

```json
{
  "name": "hermione-test",
  "version": "1.0.0",
  "description": "",
  "main": ".hermione.conf.js",
    "directories": {
        "test": "tests"
    },
  "scripts": {
    "start": "./node_modules/.bin/selenium-standalone start",
    "test": "./node_modules/.bin/hermione"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {},
  "devDependencies": {
    "chai": "^4.2.0",
    "hermione": "^2.7.0",
    "selenium-standalone": "^6.16.0"
  }
}
```
**.hermione.conf.js:**

```js
module.exports = {
    sets: {
        desktop: {
            files: 'tests/'
        }
    },

    browsers: {
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome'
            }
        }
    }
};
```

**test.hermione.js:**

```js
const assert = require('chai').assert;

describe('github', function() {
    it('should find hermione', function() {
        return this.browser
            .url('https://github.com/gemini-testing/hermione')
            .getText('#readme h1')
            .then(function(title) {
                assert.equal(title, 'Hermione2')
            });
    });
});
```

Я уже что только не перепробовал, подскажите, может что упустил.

**Comment by j0tunn** [comment]
Закоммить куда-нибудь код. Подозреваю, что проблема в путях

**Comment by shishkin17** [comment]
Вот: https://github.com/shishkin17/hermione
Но это по сути то же самое (только скрытый .hermione.conf.js не добавляется, но он есть в текстовом виде выше).
Путь до тестов пробовал менять на несуществующий - тогда ругается, так что вроде его смотрит.

**Comment by shishkin17** [comment]
> Закоммить куда-нибудь код. Подозреваю, что проблема в путях

Вот: https://github.com/shishkin17/hermione
Но это по сути то же самое (только скрытый .hermione.conf.js не добавляется, но он есть в текстовом виде выше).
Путь до тестов пробовал менять на несуществующий - тогда ругается, так что вроде его смотрит.

**Comment by j0tunn** [comment]
Попробуй в `files` указать `tests` (без слэша) или `tests/*`

**Comment by shishkin17** [comment]
> Попробуй в `files` указать `tests` (без слэша) или `tests/*`

'tests/*' - валится
'tests' и 'tests/' выполняется с нулями.

**Comment by j0tunn** [comment]
тогда закоммить в репо все файлы (включая конфиг), нужно воспроизводить. На какой ОС тесты запускаются?

**Comment by shishkin17** [comment]
> тогда закоммить в репо все файлы (включая конфиг), нужно воспроизводить. На какой ОС тесты запускаются?

Закомитить вместе с node_modules? Я просто локально ставил все, там дофига файлов.
На маке.

**Comment by j0tunn** [comment]
зависимости можно просто указать в `dependencies` или `devDependencies` в `package.json`

**Comment by shishkin17** [comment]
> зависимости можно просто указать в `dependencies` или `devDependencies` в `package.json`

Ок, тогда все готово. https://github.com/shishkin17/hermione

**Comment by sipayRT** [comment]
проверил у себя твои тесты - все работает:

 ```js
✘ github should find hermione [chrome:e03d078be030a99e30374478aa911f80] - 3528ms
Total: 1 Passed: 0 Failed: 1 Skipped: 0 Retries: 0

1) github should find hermione
   in file tests/test.hermione.js

   chrome
     ✘ AssertionError: expected 'Hermione' to equal 'Hermione2'
```

запускал командой `npx hermione`. Уточни, плз, версию node, npm

**Comment by shishkin17** [comment]
> проверил у себя твои тесты - все работает:
> 
> ```js
> ✘ github should find hermione [chrome:e03d078be030a99e30374478aa911f80] - 3528ms
> Total: 1 Passed: 0 Failed: 1 Skipped: 0 Retries: 0
> 
> 1) github should find hermione
>   in file tests/test.hermione.js
> 
>   chrome
>     ✘ AssertionError: expected 'Hermione' to equal 'Hermione2'
> ```
> 
> запускал командой `npx hermione`. Уточни, плз, версию node, npm

Node: v10.15.2
npm: 6.4.1

**Comment by shishkin17** [comment]
> проверил у себя твои тесты - все работает:
> 
> ```js
> ✘ github should find hermione [chrome:e03d078be030a99e30374478aa911f80] - 3528ms
> Total: 1 Passed: 0 Failed: 1 Skipped: 0 Retries: 0
> 
> 1) github should find hermione
>   in file tests/test.hermione.js
> 
>   chrome
>     ✘ AssertionError: expected 'Hermione' to equal 'Hermione2'
> ```
> 
> запускал командой `npx hermione`. Уточни, плз, версию node, npm

У меня даже хром не поднимается, вот все мои логи после запуска теста:

Total: 0 Passed: 0 Failed: 0 Skipped: 0 Retries: 0

**Comment by sipayRT** [comment]
а запусти тесты с переменной окружения `DEBUG=*` и скинь логи

**Comment by shishkin17** [comment]
> а запусти тесты с переменной окружения `DEBUG=*` и скинь логи

Я извиняюсь, можно поподробнее как именно?) 
В hermione нашел вот такой вариант для debug: --inspect (это не оно?)
С ним дает такой лог:

Debugger listening on ws://127.0.0.1:9229/a5eef994-668d-4c56-8e19-05c62fbb161d
For help, see: https://nodejs.org/en/docs/inspector
Total: 0 Passed: 0 Failed: 0 Skipped: 0 Retries: 0

**Comment by sipayRT** [comment]
не, просто выполни команду `DEBUG=* npx hermione`

**Comment by shishkin17** [comment]
> не, просто выполни команду `DEBUG=* npx hermione`

Выполнил, вот логи:

snapdragon:compiler initializing /Users/andrew.shishkin/Documents/Yandex.Disk.localized/Программирование/Development/Web (Mac)/Git/Hermione Test/node_modules/snapdragon/lib/compiler.js +0ms
  snapdragon:parser initializing /Users/andrew.shishkin/Documents/Yandex.Disk.localized/Программирование/Development/Web (Mac)/Git/Hermione Test/node_modules/snapdragon/lib/parser.js +3ms
  mocha:suite bail undefined +0ms
  mocha:suite timeout 60000 +5ms
  mocha:suite enableTimeouts true +1ms
  mocha:suite slow 10000 +0ms
Total: 0 Passed: 0 Failed: 0 Skipped: 0 Retries: 0

**Comment by shishkin17** [comment]
> не, просто выполни команду `DEBUG=* npx hermione`

ну что можно сказать по логам?

**Comment by shishkin17** [comment]
Хотел бы вернуться в к этому вопросу и добить.
Прокомментируете логи?
Еще заметил такую вещь: если указать несуществующую папку в "sets", то будет ругаться (значит хотя бы что-то пытается), но вот что именно в файле, который описывает тест, ему как абсолютно все равно - можно написать любой невалидный код и даже не тест вовсе - ничего не упадет, но будут нули везде как всегда.
Может это наводит на какие мысли?

**Comment by j0tunn** [comment]
@sipayRT 
В общем проблема в скобочках в названии папки `Web (Mac)`. Если убрать хотя бы одну, то все начинает запускаться. 
Переименуй директорию во что-нибудь менее напряжное для баша (без символов, которые необходимо экранировать при вводе в консоли).

Почему так пока не знаю, @sipayRT @DudaGod как будет время - подебажьте, пожалуйста. Похоже на баг где-то в используемых модулях

**Comment by shishkin17** [comment]
О, Боги! И правда заработало! Спасибо огромное!!! Столько часов мучений, а все из-за пары скобок. Я бы точно не подумал на это.
