### ISSUE TITLE
Не работает опция compositeImage: true в конфиге

### ISSUE THREAD

**Issue by ph4ud** [gemini-testing/hermione#412]
Пытался сделать полностраничный скриншот во время теста
Добавил опцию  compositeImage: true в конфиг, как вы советовали в другой issue.
Но скриншот все равно делается не всей страницы, а только того, что влезает в окно браузера. Ошибок или warning тест при этом не выдает.
По какой причине подобное может происходить?

**Comment by j0tunn** [comment]
Нужно больше деталей:
- ось, версия инструмента
- конфиг
- тест
- можно ссылку на тестируемую страницу
- результаты прогона

Можно все это выложить куда-нибудь, чтобы можно было воспроизвести

**Comment by ph4ud** [comment]
Windows 10, Chrome 74.0.3729.169, hermione ^2.6.1
Конфиг, тест и получившийся скриншот тут 
https://github.com/ph4ud/hermione
Страница ваша - yandex.ru

**Comment by sipayRT** [comment]
@ph4ud обрати внимание на стили этой страницы - высота body выставлена в 100% и всегда будет соответствовать размеру вьюпорта
