### ISSUE TITLE
Не работает функция assertView, если в качестве аргумента передать значение ключа объекта

### ISSUE THREAD

**Issue by ph4ud** [gemini-testing/hermione#413]
Есть объект вида
report = {
 numericVariable: {
    path: 'xTabBasicFeatures/numericVariable',
    element: '.co-st-dashboard__widget:nth-child(1)',
    ignore: '.co-st-r-frequency-table__row-cell'
  }
}

Если вызвать 
        .assertView(report.numericVariable.path, report.numericVariable.element, {
          ignoreElements: [report.numericVariable.ignore],
        })

тест падает с ошибкой
TypeError: Cannot read property 'path' of undefined

При этом:
1) вызов внутри теста console.log(report.numericVariable.path) спокойно возвращает значение ключа
2) при вызове

 .assertView('xTabBasicFeatures/numericVariable', '.co-st-dashboard__widget:nth-child(1)', {
          ignoreElements: ['.co-st-r-frequency-table__row-cell'],
        })

тест выполняется без ошибок

**Comment by j0tunn** [comment]
Скинь полный лог теста (включая место где работает вывод `console.log`

**Comment by ph4ud** [comment]
При запуске теста с "обычным" assertView лог выглядит так 

LOG: xTabBasicFeatures/numericVariable
✓ pilot2 simple test2 [tenta69:416f8e8bfe3bdf800c74cb9da8064273] - 30104ms
Total: 1 Passed: 1 Failed: 0 Skipped: 0 Retries: 0

При запуске с "проблемным" - так 

✘ pilot2 simple test2 [tenta69:326b989dc068bc5d5ae766d78167280e] - 7707ms
Total: 1 Passed: 0 Failed: 1 Skipped: 0 Retries: 0

1) pilot2 simple test2
   in file tests\scr-xtab-basic-features.js

   tenta69
     ✘ TypeError: Cannot read property 'path' of undefined
    at Object.<anonymous> (C:\tests\geminiTests\tests\scr-xtab-basic-features.js:13:44)
    at Object.tryCatcher (C:\tests\geminiTests\node_modules\bluebird\js\release\util.js:16:23)
    at Object.<anonymous> (C:\tests\geminiTests\node_modules\bluebird\js\release\method.js:15:34)
    at ExecutionThread._call (C:\tests\geminiTests\node_modules\hermione\lib\worker\runner\test-runner\execution-thread.js:46:53)
    at ExecutionThread.run (C:\tests\geminiTests\node_modules\hermione\lib\worker\runner\test-runner\execution-thread.js:28:24)
    at TestRunner.run (C:\tests\geminiTests\node_modules\hermione\lib\worker\runner\test-runner\index.js:47:35)
    at <anonymous>

**Comment by j0tunn** [comment]
Прости, опечатался: нужен код теста

**Comment by ph4ud** [comment]
let report = '';
describe('pilot2', () => {
  it('simple test2', function() {
    return (
      this.browser
        .getMeta('testsData')
        .then((data) => report = require(`../testData/xTab/`+data))
        .getMeta('env')
        .then((env) => this.browser.prepareDashboard(report, env))
        .then(() => console.log('LOG: '+report.numericVariable.path))
        .assertView(report.numericVariable.path, report.numericVariable.element, {
             ignoreElements: [report.numericVariable.ignore],
        })
    );
  });
});

**Comment by j0tunn** [comment]
Проблема в коде теста. А именно в порядке выполнения кода:
- сначала выполняется подстановка значений `report.numericVariable.path`, `report.numericVariable.element` и `report.numericVariable.ignore`. И эти значения передаются в `assertView`. На этом этапе `report === ''`
- затем начинают выполняться тела асинхронных функций и в частности `report = require('../testData/xTab/'+data)`

`console.log` корректно отрабатывает, т.к. находится внутри коллбэка `then`.

Самый простой способ починить - позвать `assertView` также внутри коллбэка:
```js
    .then(() => this.browser.assertView(report.numericVariable.path, report.numericVariable.element, {
         ignoreElements: [report.numericVariable.ignore],
    });
```

Понятней будет, если переписать это все на `async-await`:
```js
let report = '';
describe('pilot2', () => {
  it('simple test2', async function() {
    const data = await this.browser.getMeta('testsData');
    report = require(`../testData/xTab/${data}`);

    const env = await this.browser.getMeta('env');
    await this.browser.prepareDashboard(report, env);
    
    console.log('LOG: '+report.numericVariable.path));
    await this.browser.assertView(report.numericVariable.path, report.numericVariable.element, {
         ignoreElements: [report.numericVariable.ignore],
    });
  });
});
```

Советую уделить внимание тому, как в js работают промисы.

Еще можно унести подключение `data` в `beforeEach`

**Comment by ph4ud** [comment]
Помогло, спасибо
