### ISSUE TITLE
Как сохранить в файл результат сравнения скриншотов?

### ISSUE THREAD

**Issue by ph4ud** [gemini-testing/hermione#415]
Не нашел ни в readme, ни в конфигах способ сохранить куда-нибудь результат сравнения скриншотов. Чтобы можно было самому, своими глазами, посмотреть difference. Как это сделано, например, в resemble.js. Подскажите пожалуйста, есть ли такой способ, и если да - как его применять?

**Comment by sipayRT** [comment]
Привет

Для этого есть плагин [html-reporter](https://github.com/gemini-testing/html-reporter)
Он сгенерит тебе страницу, на которой можно будет посмотреть на результаты
