### ISSUE TITLE
Suggestion: Add html info option to assertView 

### ISSUE THREAD

**Issue by R1ZEN** [gemini-testing/hermione#422]
Привет!

Часто возникает потребность узнать состояние html которое находится на скришоте. Воспроизводить все ручками долговато, а иногда просто нужно узнать какие классы применяются к блокам или какие значения атрибутов на тестируемом браузере.

Хотелось бы видеть эту функциональность в html-reporter ))

**Comment by sipayRT** [comment]
привет

так ты можешь написать свой плагин (или просто добавить команду в конфиге), который будет добавлять кастомную команду, сохраняющую необходимую информацию для теста. Например, ты можешь добавить в мету (инструкция - https://github.com/gemini-testing/hermione#sharable-meta-info) нужную информацию и она автоматически прорастет в отчет в раздел Meta

**Comment by DudaGod** [comment]
@R1ZEN предложенный вариант от @sipayRT тебе подходит?

**Comment by R1ZEN** [comment]
@DudaGod Да
