### ISSUE TITLE
Возможность перехода на следующий тест

### ISSUE THREAD

**Issue by Alexx1992** [gemini-testing/hermione#431]
Есть кастомная функция в prepareBrowser, например:
```
function customFunc(url) {
  return this.url(url)
    .elements('#id')
    .then(element => {
      const hasElement = element.value.length;
      return hasElement ? .....
     })
     .pause(500)
     .execute()
     ...........
}
```
Подскажите, есть ли возможность завершить текущий тест (без какой-либо ошибки, просто пропустить) и перейти на следующий если, например, hasElement будет равна 0
В документации ни к hermione, ни к webdriverio, нужного не нашёл. Метод end() полностью завершает весь процесс тестов и не особо подходит. Спасибо!

**Comment by j0tunn** [comment]
Из кастомной команды осуществить выход из теста невозможно, можно выйти из тела теста, просто осуществив `return` из его коллбэка. При этом тест будет считаться успешно пройденным.

Можно пойти другим путем: из команды бросать какое-то определенное исключение. Все тесты завернуть в какой-нибудь враппер и в нем отлавливать это исключение. Что-то вроде такого:
```js
function test(title, cb) {
    it(title, async function() {
        try {
            await cb.call(this);
        } catch(e) {
            if (e instanceof MyError) {
                // ничего не делаем, тест считается успешно прошедшим
            } else {
               throw e;
            }
        }
    });
}

describe('foo', () => {
    test('bar', function() {
        // тело теста
    });
});
```
