### ISSUE TITLE
PO при написании тестов 

### ISSUE THREAD

**Issue by Tes10** [gemini-testing/hermione#435]
Доброго времени суток!
Я не так часто пишу на JS, но гуглом пользуюсь не плохо и примеров использования page object pater'на с Гремионой не нашёл.(

Объявляю в отдельном классе элементы :
![image](https://user-images.githubusercontent.com/18033776/62949331-ac2ce400-bdee-11e9-9dd8-a21b6055df27.png)
Потом пытаюсь оперировать ими:
![image](https://user-images.githubusercontent.com/18033776/62949423-d2eb1a80-bdee-11e9-9f93-b031af5309ac.png)

Как я понимаю, по причине того что browser существует только в контексте теста, получаю:
![image](https://user-images.githubusercontent.com/18033776/62949560-134a9880-bdef-11e9-9811-9040b6438b80.png)

Подскажите ,ЧЯДНТ?

**Comment by sipayRT** [comment]
привет

по твоему примеру вообще не понятно откуда в тесте появился инстанс класса firstStepPage.
Внутри класса ты используешь переменную `browser`, но в сам класс ее никак не передаешь

**Comment by Tes10** [comment]
@sipayRT 
Пробросил через конструктор this.browser из теста и все заработало. Ларчик просто открывался. Спасибо
