### ISSUE TITLE
Переопределить параметры в конфиге

### ISSUE THREAD

**Issue by Eccentric74** [gemini-testing/hermione#440]
Есть ли какая-то возможность для определенных тестов переопределять глобальные конфиги.
В частности интересует переопределение параметра system -> parallelLimit 
Нужно подобное для работы с аккаунтом пользователя, но при этом не хотелось бы, чтобы остальные тесты выполнялись так же последовательно. 
Или может есть какой-то другой способ сделать тесты последовательными (в том числе и в разных браузерах) ?

**Comment by sipayRT** [comment]
для последовательного выполнения тестов есть плагин https://github.com/gemini-testing/hermione-sequential-tests-run

но запускать в одном ране и общие тесты, и тесты со строгой последовательность не получится, т.к. parallelLimit - это общая опция для всех браузеров. для этого нужен будет отдельный запуск
