### ISSUE TITLE
Ошибка Out of the bounds на конкретном сайте

### ISSUE THREAD

**Issue by alena-p** [gemini-testing/hermione#444]
Столкнулись с тем, что использование метода assertView для конкретного веб-сайта (http://new.mcrm.ru) завершается с ошибкой Out of the bounds, если элемент находится в структуре страницы ниже, чем высота вьюпорта браузера (т.е. срабатывает скролл до элемента). Помогите разобраться

**Comment by DudaGod** [comment]
Привет.

Ошибка `out of the bounds`, говорит, что элемент, который ты пытаешься заскриншотить находится за пределами страницы. Если это ожидаемое поведение, то необходимо использовать опцию `allowViewportOverflow`. Подробнее про имеющиеся опции для команды `assertView` можешь прочитать тут - https://github.com/gemini-testing/hermione#assertview.
