### ISSUE TITLE
Update webdriverio

### ISSUE THREAD

**Issue by egoroof** [gemini-testing/hermione#455]
Hi,

webdriverio in hermione soo old, could you update it to the latest version?

We cannon launch firefox, it causes error like this https://bugzilla.mozilla.org/show_bug.cgi?id=1518376

**Comment by sipayRT** [comment]
> webdriverio in hermione soo old

version v5 doesn't support all old browsers. 

> We cannon launch firefox, it causes error like this https://bugzilla.mozilla.org/show_bug.cgi?id=1518376

this command is deprecated. you should use performActions instead. wdio@5.x only has command that decorate it - https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/commands/element/moveTo.js#L33-L38

**Comment by elgalu** [comment]
Hi, thanks for this project!

Are there plans to upgrade your [webdriverio fork](https://github.com/gemini-testing/webdriverio) to v5 ?

**Comment by sipayRT** [comment]
hi

will try to update it soon

**Comment by Christopher-Hayes** [comment]
Hi, Hermione seems really nice and I am already planning to use Mocha+Chai which is perfect. But, WebDrive.io v4 is a bit of a deterrent. Building a test suite with an outdated API is a little too scary for me. If the upgrade comes soon, I'll definitely look at using Hermione. Thanks.

**Comment by web-padawan** [comment]
There is a webdriver version 6 released already. So maybe now it's time to consider that one 🤔

**Comment by sipayRT** [comment]
hi

I tried to do it in my free time, but failed. So, this work will be planned to our main working time

**Comment by HamsterCoder** [comment]
Any changes so far, old webdriver is one of the reasons we are ready to give up on this tool =(

**Comment by DudaGod** [comment]
Hello.

We will migrate on a new wdio version very soon.

**Comment by DaRuski** [comment]
What is the definition of 'very soon'? :)

**Comment by DudaGod** [comment]
Very soon - it's in this year, i hope =)

The main problem here that a lot of projects use api from v4 which is completely different from v6. So before we update wdio we should write hermione plugin, which would ensure the implementation of old commands through new ones in order to ensure a smooth transition to the new hermione version.

**Comment by rifler** [comment]
can there projects use old major version of hermione?

**Comment by DudaGod** [comment]
> can there projects use old major version of hermione?

Yes, they can. But in this case we will have to support few branches (with old and with new wdio). Therefore this is not the best option for us.

**Comment by EvgenyArtemov** [comment]
Any updates 

> Hello.
> 
> We will migrate on a new wdio version very soon.

Any updates?

**Comment by DudaGod** [comment]
> Any updates?

We have already written a plugin [hermione-wdio-migrator](https://github.com/gemini-testing/hermione-wdio-migrator) with commands from wdio@4 that used commands from wdio@6.

And now we are at the final stage of work on the codemod, which will transform tests to async-await style and use separate call of browser commands instead of chaining them. In wdio@6 chaining of browser commands does not work...

It seems that new version of hermione with wdio@6 will be ready in about 2 weeks.

**Comment by EvgenyArtemov** [comment]
> > Any updates?
> 
> We have already written a plugin [hermione-wdio-migrator](https://github.com/gemini-testing/hermione-wdio-migrator) with commands from wdio@4 that used commands from wdio@6.
> 
> And now we are at the final stage of work on the codemod, which will transform tests to async-await style and use separate call of browser commands instead of chaining them. In wdio@6 chaining of browser commands does not work...
> 
> It seems that new version of hermione with wdio@6 will be ready in about 2 weeks.

Great news!!! Thank you!!!

**Comment by DudaGod** [comment]
New version with wdio@7 under the hood is already published - hermione@4.0.0-alpha.0.
At the moment we are at the stage of adding it to one of our very large projects (~ 30k tests). When we are done with the update, we will write detailed documentation on migration to the new version.

**Comment by sipayRT** [comment]
Current status:
- from hermione@4.x we already use wdio@7.x
- from hermione@7.x we will use wdio@8.x (in progress)
