### ISSUE TITLE
AssertView для двух скриншотов сделанных во время теста (без эталона)

### ISSUE THREAD

**Issue by Dino1992** [gemini-testing/hermione#467]
Привет! Есть потребность во время теста ходить на 2 разных урла, на которых один и тот-же контент, но может по разному работать SSR, в итоге нужно сравнить во время теста, что страницы выглядят одинаково. Есть какое-то решение из коробки?

**Comment by j0tunn** [comment]
По идее нужно 2 запуска hermione:
1. В режиме сохранения эталона на одном урле
2. В режиме тестирования на втором

В самой hermione возможности ходить по двум разным урлам нет.

**Comment by Dino1992** [comment]
Спасибо за ответ. Попробую так.
