### ISSUE TITLE
Downloading from npm fails

### ISSUE THREAD

**Issue by butteredptarmigan** [gemini-testing/hermione#468]
Context:
- Windows 10
- Python 3 provided by Anaconda
- Selenium standalone set up successfully as requested

I was trying to download Hermione via npm, while this bug appeared:
```
> png-img@2.2.1 install (project)\node_modules\png-img
> node-gyp rebuild


(project)\node_modules\png-img>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )         
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: C:\Users\Me\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd (project)\node_modules\png-img
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

Npm says the origin of this bug is external. I suppose it has nothing to do with Hermione itself, but rather one of the dependencies (png-img?) using obsolete syntax of python while not specifying which version to use. But I would like to inform you on this anyway – it may be something on my environment's side as well, but if it is this dependency that is faulty, you might want to take a look. The same bug appears while trying to download globally.

### Edit
I have done some research, looked up logs, and it seems like my issue is similar to gemini-testing/png-img#34. Below, there is a copy of last lines from my log.

```
5620 error code ELIFECYCLE
5621 error errno 1
5622 error png-img@2.2.1 install: `node-gyp rebuild`
5622 error Exit status 1
5623 error Failed at the png-img@2.2.1 install script.
5623 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by DudaGod** [comment]
@sipayRT you recently installed hermione in windows. Have you seen a similar problem, and if so, how did you fix it?

**Comment by sipayRT** [comment]
I've never seen this before
Issue about node-gyp build fails from https://github.com/gemini-testing/png-img/issues/34 it's about wrong path to `msbuild.exe`
@butteredptarmigan can you switch your python build to default version?

**Comment by butteredptarmigan** [comment]
Sure, I'll try, thanks for the tip!

**Comment by DudaGod** [comment]
> Sure, I'll try, thanks for the tip!

Is there any news?

**Comment by DudaGod** [comment]
Closed due to not activity.
