### ISSUE TITLE
windowSize doesn't work

### ISSUE THREAD

**Issue by piotr-s-brainhub** [gemini-testing/hermione#475]
I set `windowSize: '5200x3600'` but the actual image dimensions are `926x301` (https://2406-116013398-gh.circle-artifacts.com/0/hermione-reports/index.html).

**Comment by DudaGod** [comment]
Hello.

Your link is not available - https://2406-116013398-gh.circle-artifacts.com/0/hermione-reports/index.html. Moreover can you send minimal reproducible case and your hermione config in order to check your problem.

**Comment by piotr-s-brainhub** [comment]
We decided to use Cypress instead so I don't have time to test this issue.

**Comment by DudaGod** [comment]
Okay. I understand you. I checked that case and in my test project I did not reproduce the problem.

Good luck.
