### ISSUE TITLE
Запуск тестов из определенной папки

### ISSUE THREAD

**Issue by wayheming** [gemini-testing/hermione#476]
Здравствуйте подскажите как можно запустить тесты из одной папки где например 5 файлов с тестами. Раньше я использовал gemini и команда была такая `gemini gui tests\demo\booking` сейчас пользуюсь командой которая запускает все тесты `hermione gui --config ../../.hermione.custom.conf.js` где в конфиге прописано http://prntscr.com/re7lqx Подскажите пожалуйста правильную команду или настройку конфига.

**Comment by sipayRT** [comment]
> Раньше я использовал gemini и команда была такая gemini gui tests\demo\booking

привет. в гермиону все ровно так же - просто передаешь путь аргументом

**Comment by wayheming** [comment]
Пробовал как написано в примере `hermione tests/func/mytest.js` `hermione gui --config ../../.hermione.custom.conf.js tests\demo\booking` и `hermione gui --config ../../.hermione.custom.conf.js tests\demo\booking\home.js` но получаю ошибку Html-reporter runtime error: Error: Cannot find files by masks in sets

**Comment by wayheming** [comment]
Если пишу hermione gui --config ../../.hermione.custom.conf.js tests\demo\booking запускается gui где все тесты со всех папок

**Comment by wayheming** [comment]
Ага я понял нужно удалить с конфига sets и по команде `hermione gui --config ../../.hermione.custom.conf.js tests/demo/booking` работает. Прошу прощения за беспокойство) Спасибо за быстрые ответы
