### ISSUE TITLE
Using Selenium within Hermione tests

### ISSUE THREAD

**Issue by melanchall** [gemini-testing/hermione#480]
I can't find any examples or manuals that shows how to use Selenium within Hermione tests especially in call chains like this:

```js
it('dashboard opened', function () {
    return this.browser
	  .click(signInButton)
	  .assertView('Sign In dialog opened', signInDialog);
  });
```

For example, how can I type text in some text box in this test?

**Comment by DudaGod** [comment]
Hello.

You should look at wdio API - http://v4.webdriver.io/api.html, which is used inside hermione.

> For example, how can I type text in some text box in this test?

You should look at `setValue` - http://v4.webdriver.io/api/action/setValue.html.
