### ISSUE TITLE
Update mocha to latest version

### ISSUE THREAD

**Issue by web-padawan** [gemini-testing/hermione#481]
Hi, and thanks for the great tool!

I would like to ask if you have plans to upgrade `mocha` to latest version.
There are at least two vulnerabilities related to it mentioned in #456

Based on the changelog, most of breaking changes in `mocha` has been related to dropping old Node.js versions and old browser versions (mostly, old IE11). Do you still support these?

Or maybe, do you have any particular reasons to stay on the old version?
https://github.com/gemini-testing/hermione/blob/43f5e188d46e4dce1b855fdc23b8e614581d482a/package.json#L46

If you could provide more information, I would be happy to contribute.

**Comment by DudaGod** [comment]
Hello.
You are welcome.

Currently we use mocha only like a test reader therefore, it seems that these major changes should not break anything. But first of all it should not slow down reading tests.

I try to update mocha here - https://github.com/gemini-testing/hermione/pull/492.

**Comment by web-padawan** [comment]
Looks like `mocha` is also updated to `^7.1.2` by https://github.com/gemini-testing/gemini-core/pull/70

**Comment by DudaGod** [comment]
In gemini-core mocha is used only as test runner and installed in dev deps. So it was much easier to update.

**Comment by AlexisVK** [comment]
Hello. It would be really great if you will proceed with this PR. I have only 1 critical audit warning and it is related to old mocha version

**Comment by DudaGod** [comment]
> Hello. It would be really great if you will proceed with this PR. I have only 1 critical audit warning and it is related to old mocha version

Hello. We will try to do it. Last time there were a lot of problems when updating the version.

**Comment by DudaGod** [comment]
We have already updated mocha in this PR - https://github.com/gemini-testing/hermione/pull/589. So I close it.
Thank you.
