### ISSUE TITLE
Screens sometimes do not equals

### ISSUE THREAD

**Issue by dmepty** [gemini-testing/hermione#482]
Sometime I get different pictures (bottom)
Good - https://imgur.com/a/JQkmIgW
Bad - https://imgur.com/a/JxfaPXp

My config:

```
module.exports = {
    baseUrl: '...',
    gridUrl: 'http://127.0.0.1:4444/wd/hub',
    compositeImage: true,
    sessionsPerBrowser: 3,
    browsers: {
        chrome: {
            screenshotsDir: GetPath,
            desiredCapabilities: {
                browserName: 'chrome',
                screenshotMode: 'fullpage',
                assertViewOpts: {
                    captureElementFromTop: true,
                    allowViewportOverflow: true
                },
                chromeOptions: {
                    args: [
                        '--headless',
                        '--window-size=1920,1080'
                    ]
                }
            }
        },
    },
    plugins: {
        'html-reporter/hermione': {
            enabled: true,
            path: 'report',
            defaultView: 'all'
        }
    }
};
```
Test is simple, just capture `html` element.

Is it bug or wrong config?

**Comment by huston007** [comment]
@dmepty May it be caused by "automated" toolip?
![image](https://user-images.githubusercontent.com/4318513/78558373-19c4cf00-781b-11ea-9229-5292ffa0fb49.png)

**Comment by dmepty** [comment]
@huston007 I think not, because the size is not always the same and can reach half a page

**Comment by DudaGod** [comment]
Hello.

Can you provide your test code and the address of the page you are testing?

**Comment by DudaGod** [comment]
Closed due to not activity. If there will be other questions create a new issue.
