### ISSUE TITLE
Hermione: HTML report issue

### ISSUE THREAD

**Issue by rafeekabid** [gemini-testing/hermione#484]
Team,
I am facing report issue in hermione. Image is not rendered when open in crome(image is not load). But same file works well in firefox. I checked image address whic is causing issue in chrome browser.
Address:  "file:///D:/Temp/Test/Hermione-CSS-Regression-Testing-Example-master/my/hermione-reports/images%5C8c6858d%5CWhole%20page%5CchromeMobile~ref_0.png"

Here encoded address is populating in chrome browser like %5C, %20. 

Anyone help me on this if you have any solution.

Regards,
Rafeek

**Comment by sipayRT** [comment]
Hi
This is problem of `html-reporter`. See https://github.com/gemini-testing/html-reporter/issues/133

**Comment by rafeekabid** [comment]
> Hi
> This is problem of `html-reporter`. See [gemini-testing/html-reporter#133](https://github.com/gemini-testing/html-reporter/issues/133)

Is there any solution?  As far as my understanding, this #133 issue doesn't have any solution. correct me if i am wrong

**Comment by sipayRT** [comment]
you can ask it at https://github.com/gemini-testing/html-reporter/issues/133, not here

**Comment by rafeekabid** [comment]
> you can ask it at [gemini-testing/html-reporter#133](https://github.com/gemini-testing/html-reporter/issues/133), not here

Thank for you reply.I have posted this issue in #465 
However, In my project, I am doing tools evaluation for visual tesing in one of our client.  I am analysing this hermione tools using "https://brainhub.eu/blog/regression-testing-with-selenium/"
and its working fine. But still have few calrification and would be greate if ou clarify those
1) What are the browser support hermione?  my understanding is (Chrome,Firefox,IE). list me if anything else.

2) Unnecessarily generate empty folder in my root directory “ \images\8c6858d\Whole page” .even I setup report plugin path is “My/Hermione-report”.

Looking forard your response.
Regards,
Rafeek

**Comment by sipayRT** [comment]
> What are the browsers support by hermione? 

Opera12 (will drop soon), IE9-IE18, Chrome, Firefox, CromeMobile(on Android), YandexBrowser, partly iOs SafariMobile. 

> Unnecessarily generate empty folder in my root directory “ \images\8c6858d\Whole page” .even I setup report plugin path is “My/Hermione-report”.

I think you have some problem with html-reporter config. You should ask about it also in https://github.com/gemini-testing/html-reporter/ repo
