### ISSUE TITLE
Hermione : visual testing issue

### ISSUE THREAD

**Issue by rafeekabid** [gemini-testing/hermione#485]
In my project,  doing tools evaluation for visual testing. I am analyzing this hermione tools using "https://brainhub.eu/blog/regression-testing-with-selenium/"
and its working fine. But still have few clarification and would be great if anyone clarify those
1.	What are the browsers support by hermione? my understanding is (Chrome, Firefox, IE). list me if anything else.
2.	Unnecessarily generate empty folder in my root directory “ \images\8c6858d\Whole page” .even I setup report plugin path is “My/Hermione-report”.
Looking forward your response.

**Comment by DudaGod** [comment]
Hello.
> What are the browsers support by hermione? my understanding is (Chrome, Firefox, IE). list me if anything else.

Hermione can run tests in:
- Chrome (desktop, pad/phone running in android emulator using appium);
- Firefox;
- IE 10, 11, Edge;
- Opera;
- Safari (desktop?, pad/phone in iOS simulator - there is few bugs that we will fix soon);
- Android applications (but for each application you should write plugin to work with native elements);

> Unnecessarily generate empty folder in my root directory “ \images\8c6858d\Whole page” .even I setup report plugin path is “My/Hermione-report”.
Looking forward your response.

It's strange. Can you provide more information about your environment, what command you run and after what action this directory is appear in your root folder?

**Comment by DudaGod** [comment]
Closed due to not activity. If there will be other questions create a new issue.
