### ISSUE TITLE
Problem with types

### ISSUE THREAD

**Issue by AStaroverov** [gemini-testing/hermione#506]
Problem:
In index.d.ts you import mocha types
```
/// <reference path='./mocha/index.d.ts' />
```
Also we declarate ```it``` in ```global.d.ts```
```
declare const it: Hermione.Test Definition;
```
and now we have multiple declaration  for ```it``` with different  declaration.

Solution:
Export from hermione methods like it, describe, etc.

It allows control types for hermione, especially if we have different interface (our case) or our global types cross with another test libraries (F.E. in our project we have jest and hermione and both have declarations for it, describe and others)

**Comment by DudaGod** [comment]
Hello.

I will look at this problem. Thank you.

**Comment by DudaGod** [comment]
In Jest@24.9.0 global types does not conflict with mocha types anymore.
