### ISSUE TITLE
При повторном запуске assertView не срабатывает compositeImage

### ISSUE THREAD

**Issue by WishHunter** [gemini-testing/hermione#513]
Добрый день. 

**.hermione.conf.js**
`module.exports = {
  sets: {
    references: {
      files: '../tests/reference/*.js'
    }
  },

  browsers: {
    chrome: {
      desiredCapabilities: {
        browserName: 'chrome' 
      },
      windowSize: '1920x1024',
      compositeImage: true,
      screenshotDelay: 2000,
      screenshotsDir: '../tests/reference/images',
      assertViewOpts: {
        ignoreElements: ['.js-notifications-popup'],
        allowViewportOverflow: true
      }
    }
  },
};`

**test.js**
`describe('tasks', () =>
  it('barcelona', function() {
    return this.browser
      .url('https://localhost:3000/')
      .click('.js-popup-gdpr .js-popup-close')
      .assertView('barcelona-1920', 'html')
      .setViewportSize({
          width: 1024,
          height: 768
        })
      .assertView('barcelona-1024', 'html')
      .setViewportSize({
        width: 768,
        height: 1024
      })
      .assertView('barcelona-768', 'html')
      .setViewportSize({
        width: 320,
        height: 568
      })
      .assertView('barcelona-320', 'html');
  })
);
`

При таких настройках первый assertView сохраняет склейку скриншотов всей страницы, второй 'bercelona-1024' уже сохраняет скриншот только области видимости, третий 'barcelona-768' сохраняет всю страницу, четвертый 'barcelona-320' вообще сохраняет только склейку половины страницы.

В чем может быть проблема?

**Comment by DudaGod** [comment]
Привет.

Пришли получившиеся скриншоты. Сходу проблемы не вижу. И можешь предоставить минимальный кейс для воспроизведения?

**Comment by WishHunter** [comment]
Привет.

1920: https://prnt.sc/ttvwjn
1024: https://prnt.sc/ttvx2l - обрезает
768: https://prnt.sc/ttvxfy
320: https://prnt.sc/ttvxtf - так же обрезает

Проверял на странице https://fbs.com/landing/barcelona/

При этом на странице https://fbs.com/landing/cent/ отрабатывает нормально, и меду скринами не плавный скролл идет.

Но так же на этом сайте: https://tinypng.com/ вообще не скролит а делает скриншоты только области видимости

Заранее спасибо

**Comment by WishHunter** [comment]
Блин, прошу прощения, после того как написал, сам догадался в чем проблема. В навешанных стилях на 'html' :( 
А именно в стиле scroll-behavior: smooth;

Спасибо за ответы!

**Comment by DudaGod** [comment]
Пожалуйста.

По поводу:
> Но так же на этом сайте: https://tinypng.com/ вообще не скролит а делает скриншоты только области видимости

На этом сайте тебе нужно `body` скриншотить, а не `html`. Так как на нем размер `html` - это как раз один вьюпорт.
