### ISSUE TITLE
hermione + CSS Modules

### ISSUE THREAD

**Issue by ValeryVS** [gemini-testing/hermione#515]
Есть приложение на create-react-app.
В нём storybook.

CSS используется в виде CSS модулей.
После применения [css-loader](https://github.com/webpack-contrib/css-loader) в webpack и работы функции [getCSSModuleLocalIdent из react-dev-utils](https://github.com/facebook/create-react-app/blob/3d74b79de0ca40d3e89531207f8064a17207bfb8/packages/react-dev-utils/getCSSModuleLocalIdent.js#L13)
класс `.root` из файла `item/index.module.scss` получается `item_root__7kujw`.

Хочется использовать его как-то так.

```typescript
import styles from '../index.module.scss';

describe('BookingItem', function () {
  it('visual', function () {
    return this.browser
      .url('/iframe.html?id=bookingitem--default')
      .waitForVisible(styles.root)
      .assertView('size_m', styles.root);
  });
});
```

Можно добавить какой-нибудь loader или что-то ещё для hermione, чтобы получить правильный селектор?

Подозреваю, что можно было бы сделать какую-то обёртку над [css-loader](https://github.com/webpack-contrib/css-loader) с теми же настройками. И далее вызывать
```typescript
import loadCSS  from 'loadCSS';

const styles = loadCSS('../index.module.scss');
```

Можно, наверное, ещё проще. Взять код [getCSSModuleLocalIdent из react-dev-utils](https://github.com/facebook/create-react-app/blob/3d74b79de0ca40d3e89531207f8064a17207bfb8/packages/react-dev-utils/getCSSModuleLocalIdent.js#L13) и проктидывать в неё путь до файла и название класса.

Может быть кто-то уже делал что-то подобное?

**Comment by DudaGod** [comment]
Привет.

> Можно добавить какой-нибудь loader или что-то ещё для hermione, чтобы получить правильный селектор?

Можно заюзать используя опцию `--require` - https://github.com/gemini-testing/hermione#require-modules. Но для этого нужен модуль, который налету скомпилирует твой css. Подобно тому как это делает babel - https://babeljs.io/docs/en/next/babel-register.html.

> Может быть кто-то уже делал что-то подобное?

С подобными кейсами не сталкивались.

**Comment by DudaGod** [comment]
Closed due to not activity. If there will be other questions create a new issue. Thank you.
