### ISSUE TITLE
TypeScript instructions

### ISSUE THREAD

**Issue by ValeryVS** [gemini-testing/hermione#516]
Тайпинги в пакете есть.
Но как запускать тесты в `.ts` файлах?

Добавил следующие настройки

```
  system: {
    fileExtensions: [
      '.ts',
    ],
  },

  sets: {
    all: {
      files: '**/__tests__/*.hermione.ts',
    },
  },
```

Попробовал запускать так
`npx hermione gui --require @babel/register`
ругается, что не может распарсить файл, если там типы.
Попробовал положить `babel.config.js` в корень (у меня его нет, так как приложение на create-react-app, там конфиг уже внутри) с конфигом бабеля тоже ругается.

Проверка типов жалуется на describe и it, так как ничего не знает про глобальные переменные hermione.
Можно написать `import 'hermione'`, но, кажется, не нужно так делать.
Возможно нужно где-то указать reference.

Нужно бы добавить инструкцию, если сейчас возможно использовать `.ts` расширение для написания самих тестов.

**Comment by DudaGod** [comment]
Привет.

Твой конфиг правильный, но для ts тебе нужно использовать ts-node/register - https://www.npmjs.com/package/ts-node. Но есть одна проблема, я когда эту фичу добавлял провтыкал прокинуть опцию `require` в воркеры, чтобы в них тоже подключить компайлеры. Это необходимо так как тесты у нас читаются как в мастер процессе, так и в воркерах. Постараюсь на днях починить. Отпишу.

**Comment by ValeryVS** [comment]
> Но есть одна проблема, я когда эту фичу добавлял провтыкал прокинуть опцию require в воркеры, чтобы в них тоже подключить компайлеры.

Возможно из-за этого сейчас не работает.
Попробовал добавить
```
// package.json

...
"scripts": {
  ...
  "hermione": "TS_NODE_PROJECT=tsconfig.hermione.json hermione --require ts-node/register"
}
...
```

Но на переменные с типами в тестах ругается.

**Comment by ValeryVS** [comment]
Как предоставить типы в файл тоже не до конца понятно.
Если не писать `import 'hermione';`, то тип для функции `it` берётся из `@types/jest`, типа из `hermione/global.d.ts` даже в списке предполагаемых в IDE нет.

Если писать `import 'hermione';`, то типы определяются нормально.

Но, опять же, ругается на `import`
```
import 'hermione';
       ^^^^^^^^^^

SyntaxError: Unexpected string
```

Видимо из-за того, что `--require @babel/register` не сработал.

**Comment by DudaGod** [comment]
Баг с тем что ts-файлы не транспилились в воркере исправили тут - https://github.com/gemini-testing/hermione/pull/558.

Чтобы не было проблем с типами для `it`, `describe` и прочего необходимо `hermione` добавить в поле `types` в tsconfig.json. Пример:
```json
{
  "compilerOptions": {
    "types": ["node", "hermione"]
  }
}
```

Issue закрываю, так как проблема исправлена.
