### ISSUE TITLE
--require can't find local file

### ISSUE THREAD

**Issue by ValeryVS** [gemini-testing/hermione#517]
Можно взять файл из пакета
`--require ts-node/register`

Но нельзя взять локальный файл
`--require ./test-require/index.js`
```
Error: Cannot find module './test-require/index.js'
```

В mocha аналогичная опция позволяет импортировать локальные файлы тоже
https://mochajs.org/#-require-module-r-module

**Comment by DudaGod** [comment]
Hello.

I will look at this problem.

**Comment by DudaGod** [comment]
Fixed here - https://github.com/gemini-testing/hermione/pull/797
