### ISSUE TITLE
Не работают стрелочные функции

### ISSUE THREAD

**Issue by Djo-djo** [gemini-testing/hermione#520]
При таком способе задания callback функции вылетает ошибка. Зато при обращении к this, можно видеть тип переменной и доступные методы.
```
describe('Desc',()=>{
    console.log(this);
    it('test',()=>{
        return this.browser.url('/');
    })
})
```
![image](https://user-images.githubusercontent.com/27286407/90225006-43b97e00-de19-11ea-8bb6-f1006ba9694d.png)

В то же время при вызове через обычные функции ошибка не появляется, но при этом методы и тип не отображаются
```
describe('Desc',function(){
    console.log(this);
    it('test',function(){
        return this.browser.url('/');
    })
})
```
Собственно вопрос: Нормальное ли это поведение и можно ли получить "лучшее" от каждого способа?

**Comment by dizel3d** [comment]
Поведение нормальное. Стрелочные функции [не имеют своего](https://learn.javascript.ru/arrow-functions#u-strelochnyh-funktsiy-net-this) `this`, а указывают на внешний `this`.

**Comment by DudaGod** [comment]
> При таком способе задания callback функции вылетает ошибка. Зато при обращении к this, можно видеть тип переменной и доступные методы.

Можешь прислать проект в котором такое поведение воспроизводится? Во втором случае с обычной функцией должны быть подсказки и доступные методы.

**Comment by DudaGod** [comment]
Closed due to not activity. If there will be other questions create a new issue. Thank you.
