### ISSUE TITLE
Skip doesn't work for before and after hooks

### ISSUE THREAD

**Issue by enotramone** [gemini-testing/hermione#53]
Hello,

``hermione.skip`` feature doesn't work for [Mocha's hooks](http://mochajs.org/#hooks). 

I have a specific test suite, where I cook some preconditions, do tests, skip a step in a specific browser and want to skip postconditions for that specific browser:

```
describe('My test suite', function() {

    before(function () {
        return this.browser
            .foo_bar_preconditions;
    });

    after(function () {
        return this.browser
            .foo_bar_postconditions;
    });

    it('First test case', function() {
        return this.browser
            .foo_bar_1st_test_case;
    });

    hermione.skip.in('ie11', 'Because it is IE');
    it('Second test case', function() {
        return this.browser
            .foo_bar_2st_test_case;
    });

});
```

At the end of the test I want to skip ``after`` hook for IE, but if I put ``hermione.skip.in`` before ``after`` hook, ``skip.in`` feature will apply to the first ``it``. It would be great if skipping could work for before and after hooks.

**Comment by sipayRT** [comment]
you don't need to do that for it. If test will be skipped no hooks will be executed for it. `before` and `after` hooks will be executed only for the first test

**Comment by enotramone** [comment]
Hooks will be executed only for the ran test, if there are ``beforeEach`` and ``afterEach`` hooks, but ``before`` and ``after`` hooks works for the whole suite. So I need to skip hooks for the whole suite no matter do I skip tests inside of it.

**Comment by sipayRT** [comment]
Can you explain for what you need to skip `before hook` section only for specific test? From your example I see that one of your test will be executed. How can you ask mocha to skip `before` section if on of the tests should be ran? It's impossible to do it with mocha (and I can't imagine a case for it).

**Comment by j0tunn** [comment]
@enotramone if you have some logic in your `before` or `after` hooks which belongs only to some (not all) tests in your describe, then you can create a separate describe with those tests and that logic in `before` (perhaps in current describe). And skip this describe

**Comment by enotramone** [comment]
I run tests on a real data, so I need to be sure that my tests don't break anything.
In ``before`` hook I check for valid preconditions for a test-suite and if necessary, I prepare some data.
Then I check a few static UI elements, but at the end of the test-suite I modify something. So, I need to return changed data to initial state in ``after`` hook.
If I skip modifications in one browser, so I don't even need a specific state for data ⇒ executions ``before`` and ``after`` hooks are unnecessary. So, why not to skip them too in order to performance.
I can move code from hooks into separate ``it`` (or separate describe, as suggested) and skip it there, but I thought, that using build in mocha's hooks are the right way. Or, in this case, it's not?

**Comment by sipayRT** [comment]
If your `before` and `after` sections was created only for specific `it`(not for all tests from describe) so it's wrong way for right testing because it can break another tests. Right solution was proposed by @j0tunn
