### ISSUE TITLE
Can Hermione manage baseline images during a screenshot comparison - same as Gemini UI

### ISSUE THREAD

**Issue by IlyasPatel** [gemini-testing/hermione#531]
In Gemini, there was capability to manage baseline images. Does Hermione have a similar feature?

**Comment by DudaGod** [comment]
Hello.

Are you talk about configure the directory to save reference images? In gemini it was - `screenshotsDir` and in hermione this option called the same - `screenshotsDir` - https://github.com/gemini-testing/hermione#screenshotsdir.

**Comment by DudaGod** [comment]
Closed due to not activity. If there will be other questions create a new issue. Thank you.
