### ISSUE TITLE
Асинхронный запрос перед тестами

### ISSUE THREAD

**Issue by Alexx1992** [gemini-testing/hermione#533]
Подскажите есть ли возможность в hermione.js сделать асинхронный запрос, до выполнения всех тестов. А потом полученные данные использовать уже в тестах. 
Пробовал через хук INIT, но по какой-то причине, в этом случае .hermione.conf.js инициализируется дважды и соответственно, нужный мне асинхронный запрос выполняется дважды. Через хук RUNNER_START, инициализация конфига уже происходила один раз, но файл тестов читался до RUNNER_START, и соответсвенно массив с данными 
 в файле сиестами был пустой.
Также пытался через Programmatic API, при выполнении метода run() код тестов выполняется, но ни какой информации в консоле нет. И промис возвращает success = false, хотя в консоле ошибок нет.
Если у кого-то есть идеи, пожалуйста поделитесь!

**Comment by DudaGod** [comment]
> Подскажите есть ли возможность в hermione.js сделать асинхронный запрос, до выполнения всех тестов. А потом полученные данные использовать уже в тестах.

Есть. Можешь воспользоваться плагином [hermione-global-hook](https://github.com/gemini-testing/hermione-global-hook). Но он будет выполняться перед каждым запуском теста. Т.е. нужно будет в твоем случае добавлять какое-то условие (флаг) про то, что данные уже есть и еще раз выполнять запрос не нужно.

Глобальных хуков `before` и `after` в гермионе нет, так как у нас все тесты выполняются параллельно и не должны зависеть друг от друга.

Пример как ты мог бы заюзать этот плагин:
```
// config
// ...
'hermione-global-hook': {
  beforeEach: async function() {
    if (!this._myAwesomeResult) {
      this._myAwesomeResult = await doSomeAsyncStuff();
  }
// ...
// test
it('some test', function() {
  const myAwesomeResult = this._myAwesomeResult;
});
```

> Пробовал через хук INIT, но по какой-то причине, в этом случае .hermione.conf.js инициализируется дважды и соответственно, нужный мне асинхронный запрос выполняется дважды. Через хук RUNNER_START, инициализация конфига уже происходила один раз, но файл тестов читался до RUNNER_START, и соответсвенно массив с данными в файле сиестами был пустой.

Данное событие выполняется как в мастер процессе, так и в воркере. Про генерируемые события в каждом из процессов можешь почитать тут - https://github.com/gemini-testing/hermione#plugins.

Чтобы выполнить твою логику на `INIT` один раз в мастер процессе необходимо заиспользовать специальный метод - `hermione.isWorker()` - https://github.com/gemini-testing/hermione#isworker. Но в этом случае данные у тебя будут только в мастер процессе, а тесты выполняются в чайлд процессах. Поэтому тебе их нужно еще через опции плагина прокинуть. Про это в доке тоже есть - (якоря нет, ищи по вхождению - `Events which are triggered in the main process and subprocesses can not share information between each other`).

В итоге твой код может выглядеть так:
```
// plugin
module.exports = (hermione, opts) => {
    hermione.on(hermione.events.INIT, async () => {
      opts.myAwesomeData = await doSomeAsyncStuff();
    });

    hermione.on(hermione.events.NEW_BROWSER, (browser) => {
        browser.addCommand('getMyAwesomeData', () => opts.myAwesomeData;
    });
};

// test
it('some test', async function() {
  const myAwesomeResult = await this.browser.getMyAwesomeData();
});
```

> Также пытался через Programmatic API, при выполнении метода run() код тестов выполняется, но ни какой информации в консоле нет. И промис возвращает success = false, хотя в консоле ошибок нет.

Тебе тут `programmatic API` не нужен. Ну и про `success = false` я не понял. Если хочешь можешь подробнее описать.

**Comment by Alexx1992** [comment]
@DudaGod спасибо, буду разбираться
