### ISSUE TITLE
hermione should exit with error if path/grep do not contain at least a single file

### ISSUE THREAD

**Issue by Glazomer** [gemini-testing/hermione#536]
## Description:
If starting Hermione will be tried with the `./node_modules/.bin/hermione gui foo_bar_bax` command, but only `foo_bar_baz` is a valid path to `hermione` file and `foo_bar_bax` is not valid (user made a typo), the program will run test for every browser. If so happens user might think that everything is going what he is expected (running only `foo_bar_baz` test), while all test being run. As a result it will take much more time than expected and may confuse the user. For preventing such situations we should throw an error that no `*.hermione.js` files were found on that path (path might be global).
Same should be done with `--grep` option. It should be expected that if no test were found with `-grep foo-bar-baz` Hermione would just exit with error code.
Error should report that path or grep didn't match a single file.

**Comment by Glazomer** [comment]
### More detailed description:

#### Path case:
Problem is that not valid paths are just ignored **without warning or error**. 
If **all paths** are not valid, Hermione treats it as empty input, and on empty input all test are being run.
Why? Because expandPaths [`glob-extra`](https://github.com/gemini-testing/glob-extra) used in `gemini-core/lib/sets-builder/index.js:77` module do not raise waring or error on not valid path. 
#### Solution: 
1. Modify [`glob-extra`](https://github.com/gemini-testing/glob-extra) package, so error or warning is raised.
2. Count how many paths given, and check the `glob-extra` return result

**Comment by DudaGod** [comment]
Fixed in hermione@3.10.2.
