### ISSUE TITLE
I Want get browser.log(type) for each test

### ISSUE THREAD

**Issue by atorbek** [gemini-testing/hermione#537]
Hi!

I want get `browser.log('browser')` for each test.

I decided to write a plugin, don't want to add `browser.log` to every test. 

How can I get `browser.log` to after each test in plugin? `NEW_BROWSER, SESSION_START, SESSION_END` not exactly what you need.

Want something like that

```
const logTypes = ['browser', 'driver', 'client', 'server'];

module.exports = async function (hermione, {path = rootPath, types = []}) {
         hermione.on(hermione.events.TEST_END, async function (browser) {
                for (const type of types) {
                        if (logTypes.includes(type)) {
                                const msg = await browser.log(type);
                                console.log(msg);
                        }
                }
        })
}
```

but `hermione.events.TEST_END` does not contain `browser`.

**Comment by DudaGod** [comment]
Hello.

You don't need to write a separate plugin. You can use our plugin - [hermione-global-hook](https://github.com/gemini-testing/hermione-global-hook), which gives you ability to set your custom `afterEach` hook in each test.

For example:
```
// ...
plugins: {
    'hermione-global-hook': {
        enabled: true,
        afterEach: async function() {
            const msg = await this.browser.log('browser');
            console.log(msg);
        }
    }
},
// ...
```

**Comment by atorbek** [comment]
Thanks, it's work)
