### ISSUE TITLE
Increasing testing speed with multiple browsers.

### ISSUE THREAD

**Issue by Glazomer** [gemini-testing/hermione#539]
Right now parallel tests are run only for the same browser. It's probably possible to make parallel even for different browsers.

**Comment by DudaGod** [comment]
> Right now parallel tests are run only for the same browser. It's probably possible to make parallel even for different browsers.

Hello.

It's true only if you use option [parallelLimit](https://github.com/gemini-testing/hermione#parallellimit) with value 1. Otherwise tests will run in all browsers simultaneously.
