### ISSUE TITLE
Test sets are not loaded since version 3.8.6

### ISSUE THREAD

**Issue by AA462709** [gemini-testing/hermione#542]
Since this week I have been trying hermione. When using the latest version (3.10.1) my tests were not loaded and executed. I tried multiple examples but all resulted in:

Total: 0 Passed: 0 Failed: 0 Skipped: 0 Retries: 0

When debugging the module I noticed that fast-glob wasn't returning the javascript files of my set and therefore no tests were found. After downgrading to version 3.8.5 of hermione everything worked perfect.

Does other people have the same issue?

**Comment by DudaGod** [comment]
Hello.

Can you send a minimal case to reproduce this bug?

**Comment by fantazer** [comment]
Та же проблема после версии 3.8.5. не видит тесты. Конфиги и тесты из документации.

**Comment by DudaGod** [comment]
Okay, I will try to reproduce this problem.

**Comment by slaeme** [comment]
Привет, у нас тоже воспроизводится, но только на Windows.

на mac os тесты находятся и исполняются

**Comment by DudaGod** [comment]
It looks like that problem in fast-glob@3 which we updated in gemini-core in version hermione@3.8.6.
Most likely it will be fixed after update mocha.

> Та же проблема после версии 3.8.5. не видит тесты. Конфиги и тесты из документации.

On which OS the problem is reproduced?

**Comment by mburdastyh** [comment]
У меня такая же проблема начиная с 4.0.0-alpha.0 до 4.1.1 при запуске на Windows 10. Версия 3.8.5 - работает.

**Comment by DudaGod** [comment]
Поправили данную проблему в следующих версиях:
- hermione@4.1.2 (под капотом используется wdio@7)
- hermione@3.11.3 (под капотом wdio@4).

Проверьте, пожалуйста, что проблема больше не воспроизводится.

**Comment by DudaGod** [comment]
The problem was fixed in versions:
- hermione@4.1.2 (with using wdio@7)
- hermione@3.11.3 (with using wdio@4)
