### ISSUE TITLE
How to realize stop on first fail

### ISSUE THREAD

**Issue by mgazizova** [gemini-testing/hermione#544]
I try to realize the stop on a first fail by intercepting hermione.event
For example, when the first test is failed I intercept TEST_BEGIN event and emit TEST_PENDING. However, after that event test runs again. 

Also I try to exit the process when the first test is failed, but statistics are not saved. 
I realized that the bail mochaOption doesn't suitable.

Maybe you know how it is realized?

**Comment by DudaGod** [comment]
Hello.

> For example, when the first test is failed I intercept TEST_BEGIN event and emit TEST_PENDING. However, after that event test runs again.

You should intercept event of test result (`TEST_FAIL` for example) and not event with info of running test.

> Also I try to exit the process when the first test is failed, but statistics are not saved.
I realized that the bail mochaOption doesn't suitable.

Try to use `hermione.halt` - https://github.com/gemini-testing/hermione#halt.

**Comment by mgazizova** [comment]
If terminate with hermione.halt until all tests have run, then statistics are not saved. On the another hand, I don’t want to wait for the results of the rest of the tests.
For the same reason I cannot use event of test result on the tests following after the first test failed.

**Comment by mgazizova** [comment]
It works. Thank you 😊
