### ISSUE TITLE
this.browser.url(...).assertView is not a function. В чем может быть проблема

### ISSUE THREAD

**Issue by poperchy** [gemini-testing/hermione#576]
test.hermione.js

`it('home', async function() {
    await this.browser
        .url('https://example.com/')
        .assertView('plain', '.home')
});`

.hermione.conf.js

```
module.exports = {
    sets: {
        desktop: {
            files: 'tests'
        }
    },
    baseUrl: 'https://example.com/',
    gridUrl: 'http://localhost:4444/wd/hub',
    compositeImage: true,

    browsers: {
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome',
            },
            windowSize: '1400x5000',
            compositeImage: true
        },
    },

    plugins: {
        'html-reporter/hermione': {
            enabled: true,
            path: 'my/hermione-reports',
            defaultView: 'all',
            baseHost: 'https://example.com/'
        }
    }
};

```
Падает ошибка после выполнения теста

✘ TypeError: this.browser.url(...).assertView is not a function

и не удается сделать эталонный скриншот. Подскажите с чем это может  быть связано. Спасибо!

**Comment by DudaGod** [comment]
Привет.

После выкатки мажора забыли примеры в доке поправить =(
Попробуй убрать чейнинг. Т.е. написать следующий код:
```
it('home', async function() {
  await this.browser.url('https://example.com/');
  await this.browser.assertView('plain', '.home');
});
```

Доку сейчас обновлю.

**Comment by poperchy** [comment]
Спасибки, всё заработало)

**Comment by DudaGod** [comment]
Пожалуйста.
Доку поправил в этом PR - https://github.com/gemini-testing/hermione/pull/577.
