### ISSUE TITLE
Sticky header for screenshot

### ISSUE THREAD

**Issue by poperchy** [gemini-testing/hermione#578]
Привет, есть ли способ из коробки (какие-то настройки) что бы избежать повторение хедера при скриншоте всей странице. На каждом скриншоте есть хедер т.к. он фиксированный. После чего скриншоты склеиваются в один и выглядит не совсем красиво. Есть ли другой способ сделать скриншот всей страницы? Спасибо

**Comment by DudaGod** [comment]
Привет.
Ты же можешь с помощью команды `execute` - https://webdriver.io/docs/api/browser/execute/ отменить у хедера режим sticky, тогда сможешь заскриншотить страницу без дублирования хедера.

**Comment by poperchy** [comment]
Gracias, я новичок в этом деле)
