### ISSUE TITLE
windowSize есть ли возможность добиться ширины в 320px

### ISSUE THREAD

**Issue by poperchy** [gemini-testing/hermione#579]
Добрый день, исходя из документации получается что нету возможности сделать скриншот именно 320px.
 При настройки конфига и указании windowSize 320, браузер ставит максимально маленькую ширину  как это возможно.
 
 И скриншот получается 481px

**Comment by DudaGod** [comment]
Привет.

А зачем тебе скриншот именно 320px? Почему просто не заскриншотить необходимый элемент ширина которого 320px?

**Comment by poperchy** [comment]
Я хочу сделать скриншот всей страницы размером 320px

**Comment by DudaGod** [comment]
Можно тогда включить мобильную эмуляцию. Пример:
```
browsers: {
  'chrome-phone': {
    desiredCapabilities: {
      browserName: 'chrome',
      browserVersion: '92.0',
      'goog:chromeOptions': {
        mobileEmulation: {
          deviceMetrics: {
            width: 320,
            height: 500
          }
        }
      }
    }
  }
}
```

**Comment by poperchy** [comment]
Спасибо большое!
