### ISSUE TITLE
Не пробрасываются headers

### ISSUE THREAD

**Issue by nikaswoon** [gemini-testing/hermione#582]
из конфига:

```
browsers: {
		chrome: {
			desiredCapabilities: {
				browserName: 'chrome' // this browser should be installed on your OS
			},
			headers: {'TEST_HEADER': 'TEST'},

		},

	}
```

В режиме дебаг в нетворке смотрю хедеры в реквестах - тестового хедера нет

Или как то иначе нужно прописывать?
из документации не очевидно(

**Comment by DudaGod** [comment]
Привет.

В доке ошибка эти header-ы передаются в request webdriver-а. Тут правильнее написано - https://webdriver.io/docs/options/#headers.

Похоже, что хедеры в http-запрос можно передать только при использовании CDP протокола. Тут примеры есть - https://github.com/webdriverio/webdriverio/issues/6361.

**Comment by DudaGod** [comment]
Поправил тут - https://github.com/gemini-testing/hermione/pull/584.

**Comment by nikaswoon** [comment]
те варианты что были предложены тут https://github.com/webdriverio/webdriverio/issues/6361 не работают в BS

> Поправил тут - #584.
@DudaGod Подскажи пожалуйста, что нужно сделать, что бы получить версию с этой правкой? Каким образом оно должно подтянуться?

**Comment by DudaGod** [comment]
> те варианты что были предложены тут webdriverio/webdriverio#6361 не работают в BS

Что такое BS?

> Подскажи пожалуйста, что нужно сделать, что бы получить версию с этой правкой? Каким образом оно должно подтянуться?

Не понял. В том PR я поправил только документацию.

**Comment by nikaswoon** [comment]
> Что такое BS?

BrowserStack

**Comment by DudaGod** [comment]
Скорей всего в browserstack использовать cdp протокол не получится, но это не точно.

Расскажи лучше какую проблему ты пытаешься решить. Может она решается другим способом.

**Comment by nikaswoon** [comment]
При запуске тестов я передаю хедер, который должен пробрасываться во все запросы в браузере. и это должно работать с Browserstack)

**Comment by DudaGod** [comment]
> При запуске тестов я передаю хедер, который должен пробрасываться во все запросы в браузере. и это должно работать с Browserstack)

А что за хедер ты передаешь? За что он ответчает?

**Comment by nikaswoon** [comment]
с помощью хедера происходит роутинг на нужную ветку.

**Comment by DudaGod** [comment]
Как время появится я посмотрю внимательнее как это можно реализовать. Сходу у меня решения нет.
