### ISSUE TITLE
Как попасть на сайт без SSL

### ISSUE THREAD

**Issue by poperchy** [gemini-testing/hermione#585]
Добрый день, на сайте нету SSL сертификата и кидает на ошибку "Подключение не защищено" где есть кнопка "Дополнительно" и  "Вернуться к безопасной странице" и т.д. Вроде бы это "strictSSL" должно помочь, но без изменений. 
Можете показать пример

**Comment by DudaGod** [comment]
Привет.

Тебе нужно выставить опцию `acceptInsecureCerts`. Пример:
```
// .hermione.conf.js
// ...
  browsers: {
    chrome: {
      desiredCapabilities: {
        browserName: 'chrome',
        browserVersion: '92.0',
        acceptInsecureCerts: true
      }
    }
  }
// ...
```

**Comment by poperchy** [comment]
Спасибо!
