### ISSUE TITLE
Поле с адресом сайта

### ISSUE THREAD

**Issue by poperchy** [gemini-testing/hermione#587]
Добрый день подскажите значимость этого поля, когда меняю  там адрес, ничего не меняется.  Можно ли получить его значение внутри теста
![image](https://user-images.githubusercontent.com/38736219/128328065-918d4759-e5cd-4464-b9b6-c81e1a884b44.png)

**Comment by DudaGod** [comment]
Добрый день.

Оно работает в паре с "глазиком". Скриншот:
![Screenshot 2021-08-05 at 13 30 11](https://user-images.githubusercontent.com/5900697/128335859-2ae8ee23-8ddd-4e7a-8f90-25839d235ce3.png)

В этом поле мы можем подменить хост и нажав на глазик перейдем на него + добавим в урл path и query параметры. Обычно используется для того, чтобы посмотреть на страницу на какой-то бете.
