### ISSUE TITLE
Выполнение 4-6 тестов из 10

### ISSUE THREAD

**Issue by poperchy** [gemini-testing/hermione#606]
Добрый, имеется проблема, не могу понять в чем именно. Имеются 20 страниц, при запуске теста скриншотинга выполняется от 6 до 8 страниц. И на последней странице пишет следующее: 
"Message" : test 'test' timed out after 60000 ms
stack: TimeoutError: est 'test' timed out after 60000 ms
Исходя из этого, ошибка видимо кроется в timeout. Подскажите как его можно увеличить, или это связанно с чем то  другим.
Спасибо!

**Comment by DudaGod** [comment]
Привет.

Чтобы такого не происходило желательно разбивать тесты на несколько.
Для увеличения таймаута можно воспользоваться опцией `testTimeout` - https://github.com/gemini-testing/hermione#testtimeout-1.

Выставить ее можно как для каждого браузера свой, так и для всех сразу на верхнем уровне рядом с `gridUrl` и другими настройками.

**Comment by poperchy** [comment]
Ещё бывает что эти тесты бесконечно идут.

**Comment by DudaGod** [comment]
> Ещё бывает что эти тесты бесконечно идут.

Необходимо включить debug логи например с помощью переменной окружения `hermione_system_debug=true`. Или явно выставить эту опцию в конфиге гермионы. Тогда по логам должно быть понятно на чем зависает тест.

**Comment by poperchy** [comment]
Спасибо за помощь!
