### ISSUE TITLE
Ошибка при нажатии "Accept"

### ISSUE THREAD

**Issue by poperchy** [gemini-testing/hermione#627]
Здравствуйте! 
Падает ошибка после нажатии кнопки "Accept", принятии эталонного изображения.
Может кто-то сталкивался с этим, и знает в чём может быть проблема.
Спасибо!

![image](https://user-images.githubusercontent.com/38736219/143604593-470a72ad-021e-4b1b-a9ae-3a4742856e6a.png)

**Comment by DudaGod** [comment]
Добрый вечер.

Нужен минимальный воспроизводимый кейс. Без него сложно сказать в чем конкретно проблема.

**Comment by poperchy** [comment]
Вознило это после обновления версии гермионы 
в конфиге прописан путь 
![image](https://user-images.githubusercontent.com/38736219/144255734-3d53c97f-6ac0-4856-90e6-23fa8c2113ed.png)

 а при accept, вроде не туда пытается сохранить изображение
![image](https://user-images.githubusercontent.com/38736219/144256338-9b86885d-b40c-4c83-8920-d373c860a783.png)

и соответственно  падает та ошибка

**Comment by sipayRT** [comment]
Проверил на 
1. hermione@5.6.2 + html-reporter@9.7.6
1. hermione@6.1.1 + html-reporter@9.7.6

Не воспроизводится. Видимо, когда-то мы это уже пофиксили
