### ISSUE TITLE
Не сканирует страницу до конца и не правильно.

### ISSUE THREAD

**Issue by exocornet** [gemini-testing/hermione#644]
Здравствуйте.

Столкнулся с проблемой, что Hermione не сканирует страницы до конца. При этом главную страницу сканирует нормально, а вот остальные страницы на сайте уже сканируются не корректно. Скролл дохоит не до конца и изображение эталонной верстки получается не корректным.

Подскажите кто сталкивался с данной проблемой и как решили?

Всем спасибо большое за помощь :)

**Comment by DudaGod** [comment]
Привет.

Предполагаю, что на этих остальных страницах используется ленивая подгрузка данных. При вызове `assertView` hermione определяет размер блока, который необходимо снять. Если блок не умещается в один вьюпорт, то выполняется несколько скриншотов с подскроллами страницы. В итоге при ленивой подгрузке данных на каждый скролл увеличивается размер страницы и об этих изменениях hermione не знает. Поэтому в этом случае нужно либо с помощью какого-то флага отключать ленивую подгрузку или же перед выполнением `assertView` проскроллить страницу с помощью команды `execute`.

**Comment by exocornet** [comment]
> execute

Привет. Я правильно понял, что мне в тесте надо прописать данную команд, что вы написали выше ? (execute)
![1](https://user-images.githubusercontent.com/57918887/174247233-000d86e2-7427-4716-a72f-e1dc939ce7ce.jpg)

**Comment by DudaGod** [comment]
Посмотрел на разные страницы сайта (https://pulse.ru), который ты тестируешь. Динамической подгрузки данных не увидел, единственное вижу ленивую загрузку изображений, но вместо них всегда есть плейсхолдеры такого же размера. Возможно стоит выставить опцию [screenshotDelay](https://github.com/gemini-testing/hermione#screenshotdelay) в конфиге гермионы, чтобы скриншоты успевали отобразиться. Но вообще их лучше стабать, т.е. на их месте отображать какую-то заглушку.

А можешь показать скриншот, который снимается и скриншот, который должен быть на самом деле? Может тогда проблема понятнее будет.

**Comment by exocornet** [comment]
> Посмотрел на разные страницы сайта (https://pulse.ru), который ты тестируешь. Динамической подгрузки данных не увидел, единственное вижу ленивую загрузку изображений, но вместо них всегда есть плейсхолдеры такого же размера. Возможно стоит выставить опцию [screenshotDelay](https://github.com/gemini-testing/hermione#screenshotdelay) в конфиге гермионы, чтобы скриншоты успевали отобразиться. Но вообще их лучше стабать, т.е. на их месте отображать какую-то заглушку.
> 
> А можешь показать скриншот, который снимается и скриншот, который должен быть на самом деле? Может тогда проблема понятнее будет.

Я извиняюсь на скрине не тот сайт был отображен. Там был тестовый вписан... сам сайт и страница непосредственно вот https://pulse.insure/bicycle/

![main](https://user-images.githubusercontent.com/57918887/174260028-178e1bda-0001-456f-9d7e-73ab525c675e.png)
![main](https://user-images.githubusercontent.com/57918887/174260062-6af386e2-c09f-4e0b-902f-fb2e78c3fb18.png)
![main](https://user-images.githubusercontent.com/57918887/174260087-4513e352-06a7-421d-a239-02f18d097dff.png)
![main](https://user-images.githubusercontent.com/57918887/174260112-c1f82c8e-7040-4ba9-9ba2-7eefd79ac27e.png)
![main](https://user-image
![main](https://user-images.githubusercontent.com/57918887/174260152-965c6566-e292-455c-a994-0484ac1843e3.png)
s.githubusercontent.com/57918887/174260138-dc912594-9565-48ab-a2ef-15a9b2dd6c87.png)
![1](https://user-images.githubusercontent.com/57918887/174260260-097e1558-fd13-4ee3-93af-90e37d8f763f.jpg)
![2](https://user-images.githubusercontent.com/57918887/174260377-6b1de47b-53a3-403b-84d7-0aba5984d569.jpg)

Вот сами некоректные скриншоты. Также прикрепил скриншоты настроек. Можно увидеть перейдя на сайт, что скрины ломаные ( https://pulse.insure/bicycle/ )

**Comment by sipayRT** [comment]
`screenshotDelay: 600` решает проблему. Если присмотреться, то при скролле header подергивается, что может быть причиной невалидных скриншотов. Если перед скриншотом выставить задержку, то гермиона стабильно скриншотит всю страницу без проблем. Это значит, что при скролле что-то все же подтормаживает и во время скриншота страница находится не в статичном положении (я воспроизвел это поведение в Safari - скролл подлагивает)

**Comment by exocornet** [comment]
> `screenshotDelay: 600` решает проблему. Если присмотреться, то при скролле header подергивается, что может быть причиной невалидных скриншотов. Если перед скриншотом выставить задержку, то гермиона стабильно скриншотит всю страницу без проблем. Это значит, что при скролле что-то все же подтормаживает и во время скриншота страница находится не в статичном положении (я воспроизвел это поведение в Safari - скролл подлагивает)

Спасибо большое. Мне помогли данные настройки.

**Comment by exocornet** [comment]
> Посмотрел на разные страницы сайта (https://pulse.ru), который ты тестируешь. Динамической подгрузки данных не увидел, единственное вижу ленивую загрузку изображений, но вместо них всегда есть плейсхолдеры такого же размера. Возможно стоит выставить опцию [screenshotDelay](https://github.com/gemini-testing/hermione#screenshotdelay) в конфиге гермионы, чтобы скриншоты успевали отобразиться. Но вообще их лучше стабать, т.е. на их месте отображать какую-то заглушку.
> 
> А можешь показать скриншот, который снимается и скриншот, который должен быть на самом деле? Может тогда проблема понятнее будет.

Ваш вариант не понял пока что как сделать. Если у вас получилось, то можете скинуть сюда. Возможно кому будет полезен, так же я протестирую его для полной уверенности его работы.

Всем спасибо :)

**Comment by sipayRT** [comment]
> Спасибо большое. Мне помогли данные настройки.

пожалуйста. Ишью тогда закрываю
