### ISSUE TITLE
Нестабильный размер скриншотов, нестабильный маленький диф на одном и том же тексте

### ISSUE THREAD

**Issue by listton** [gemini-testing/hermione#646]
Добрый день!

Проблемы две, возможно они связаны.

1. Скриншоты иногда берутся чуть-чуть разного размера или с небольшим отступом.

Например, на картинке ниже снимается скриншот карточек с изображением (изображение спрятали чёрной заглушкой). У эталона и у нового скрина захвачено немножко разное пространства над карточкой, по идеи оно не должно попадать на скрин в обоих случаях:

![Снимок экрана 2022-07-08 в 17 15 51](https://user-images.githubusercontent.com/25936385/178020571-c2336af7-06f9-4040-ad69-b4cd31096c2e.png)

А тут у нового скрина захватывается немного слева и справа от карточки:

<img width="1566" alt="Снимок экрана 2022-07-08 в 18 01 41" src="https://user-images.githubusercontent.com/25936385/178020684-f58f7f60-bf73-4af3-a677-343b1936a766.png">

То есть тесты падают из-за того, что либо (1) скриншот взят нужного размера, но с отступом => остальная часть на скрине съехала, либо (2) скрин немножко другого размера.

Воспроизводится на карточках с тенью и без тени, просто на тексте, на любых элементах.

2. Непонятного происхождения диф на тексте, например:

![Снимок экрана 2022-07-08 в 14 32 27](https://user-images.githubusercontent.com/25936385/178021458-6e034486-ac62-4ed9-b77b-733f7a1dad95.png)

![Снимок экрана 2022-07-08 в 18 08 20](https://user-images.githubusercontent.com/25936385/178021530-31a01115-4dcd-4941-8d82-03eb08b31c8c.png)

<img width="1402" alt="Снимок экрана 2022-07-11 в 15 13 07" src="https://user-images.githubusercontent.com/25936385/178261587-643489c1-bd6c-4fbc-b682-cddefff5d0a6.png">

---

Пробовали для обеих пунктов, не помогло:

- Поставить другой шрифт, мало ли
- Увеличить antialiasingTolerance
- Увеличить tolerance
- Увеличить время ожидания перед началом теста
- Убрать тень (не особо хороший вариант, т. к. в большинстве падений у проверяемых элементов нет теней, но вдруг)
- Уменьшить sessionsPerBrowser с 4 до 1

---

Конфиг:

```
module.exports = {
  sets: {
    owl: {
      files: ['tests/desktop'],
    }
  },

  baseUrl: 'http://localhost:8080',

  compositeImage: true,
  screenshotsDir: 'references',
  sessionsPerBrowser: 4,

  windowSize: {
    width: 1440,
    height: 900
  },

  browsers: {
    chrome: {
      retry: 5,
      desiredCapabilities: {
        browserName: 'chrome',
        'goog:chromeOptions': {
          args: [
            'headless',
            '--hide-scrollbars'
          ]
        }
      },
    }
  },

  plugins: {
    'html-reporter/hermione': {
      enabled: true,
      path: 'hermione-reports',
      defaultView: 'all'
    }
  }
};
```

Пример теста:

```
describe('Some tests', function() {
  this.beforeEach(async function() {
    await this.browser.url('/some/url/');

    await this.browser.execute(helpers.hideBanners);
    await this.browser.execute(helpers.hideHTMLElement, '.layout');
  });

  it('Element', async function() {
    await this.browser.$('.element').moveTo();
    await this.browser.assertView('element-name', '.element', {
      screenshotDelay: 200
    });
  });
});
```

Код хелпера `hideBanners` из примера выше:

```
function() {
  const BANNERS_SETTINGS = {
    'banner-id': {
      'display': 'none'
    },
    ...
  };
  
  const banners = [...document.querySelectorAll('.banner')];

  banners.forEach((banner) => {
    banner.style.visibility = 'hidden';

    if (BANNERS_SETTINGS[banner.id]) {
      const bannerSetting = BANNERS_SETTINGS[banner.id];
      const property = Object.keys(bannerSetting)[0];
      banner.style[property] = bannerSetting[property];
    }
  });
}
```

Код хелпера `hideHTMLElement` из примера выше:

```
function(selector) {
  const element = document.querySelector(selector);
  element.style.visibility = 'hidden';
}
```

---

Версии:

```
"chai": "4.3.6",
"hermione": "4.7.7",
"html-reporter": "8.3.0"
 ```

---

Помогите, пожалуйста, починить?

**Comment by DudaGod** [comment]
Closed due to not activity. If there will be other questions create a new issue. Thank you.

**Comment by DudaGod** [comment]
> Ничего не добавляется. html-reporter до 9 версии обновили, спасибо.

Что-то все таки должно добавляться иначе бы диффа не было. Если ты тесты гоняешь в хроме, то можешь попробовать запустить тест локально с использованием опции - `automationProtocol: devtools`. В этом случае браузер у тебя запустится локально и например после выполнения `assertView` можешь вызвать `pause` с большим значением и посмотреть в запущенном браузере, что же там со снимаемым элементом происходит (через devtools).

> Спасибо. Извините, что не вышло ответить раньше.

Пожалуйста.

**Comment by listton** [comment]
Нашла причину проблемы, вернулась написать, может кому-то пригодится.

### Плавающий диф на тексте/шрифте:

Периодически прилетала интеграция, которая грузила шрифт с таким же именем, но немного отличающийся внешне. Интеграция прилетала не в 100% случаев, шрифт перебивался раз на раз. Как вариант решения — добавить в `font-family` своим шрифтам постфикс. Что-то, что наверняка не появится в названии сторонних шрифтов, например, имя проекта.

### Плавающий размер скринов:

У карточек серый фон, при ховере появляется слабая серая тень — серый на границе тени и фона карточки очень близки. Вариант решения — перекрывать у компонентов тень при наведении и делать скрин без тени.

Только осталось некоторое непонимание/вопрос — скриншот разве не должен ограничиваться шириной и высотой указанного элемента? Вроде бы тень за его пределами не должна влиять? На сколько знаю, тень не влияет на габариты/положение элемента.
