### ISSUE TITLE
При запуске hermione ошибка webdriver : Request failed with status 200 due to WebDriver Error: unknown error: net::ERR_CONNECTION_REFUSED 

### ISSUE THREAD

**Issue by CrybabyDanChan** [gemini-testing/hermione#657]
Пытаюсь запустить гермиону на localhost( команда hermione gui ), использую storybook по адресу 'http://localhost:6006'.
Получаю следующую ошибку: 
`
ERROR webdriver: Request failed with status 200 due to WebDriver Error: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=103.0.5060.114)
  (Driver info: chromedriver=103.0.5060.53 (a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}),platform=Linux 3.10.0-1127.13.1.el7.x86_64 x86_64)
`

конфиг приложил

<img width="470" alt="Снимок экрана 2022-09-14 в 23 48 53" src="https://user-images.githubusercontent.com/48432687/190259554-ddeacd78-1a57-47ee-b181-4dd54baa6a6e.png">

**Comment by DudaGod** [comment]
Привет.

Попробуй посмотреть логи селеноида. Страница storybook-а точно доступна и открывается по урлу указанному в `baseUrl`? Еще для теста можно попробовать запустить тест в хроме с `automationProtocol: devtools`.

**Comment by CrybabyDanChan** [comment]
@DudaGod Немного больше раскопал, причина в том что я использую корпоротивный vpn, из-за этого при запуске тестов, гермиона не видит мой localhost, сталкивались ли вы уже с подобным и есть ли обходные пути?

**Comment by DudaGod** [comment]
Я правильно понял, что у тебя selenoid и storybook сервер запускается на одной машинке на которой используется корпоративный vpn?
Если отключить корпоративный vpn, то тесты начинают проходить что ли?
Открывается ли storybook локально без запуска гермионы?

У меня тоже корпоративный vpn, но если selenoid, storybook и hermione запускать на моей локальной машинке, то никаких проблем не будет.

**Comment by CrybabyDanChan** [comment]
@DudaGod Да все верно, selenoid и storybook запускаются локально, storybook открывается и без участия vpn, тесты проходят без vpn

**Comment by dicrtarasov** [comment]
С localhost проблемы часто сказаны с тем, что у него несколько адресов планы в hosts - как ipv4, так и ipv6, но серверное ПО может слушать например только IPv6 и connection refused на ipv4 localhost, поэтому указать адрес нужно через ip например, 127.0.0.1, что избавляет от данной проблемы.
