### ISSUE TITLE
New release doesn't contain updated types

### ISSUE THREAD

**Issue by epszaw** [gemini-testing/hermione#711]
Unfortunately `6.0.1` doesn't have [`TestError` type](https://github.com/gemini-testing/hermione/blob/master/typings/index.d.ts#L255) in `index.d.ts` file, but source code does.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/13414205/211866841-27ce7b28-48d3-4348-bed6-038523a8dd8b.png">

**Comment by DudaGod** [comment]
Hello. These changes released in `6.0.2`
