### ISSUE TITLE
Identified problems, with my options for solving them (Hermione 7)

### ISSUE THREAD

**Issue by kdenv2604** [gemini-testing/hermione#777]
I used Hermione 7, and identified a number of problems that I managed to solve for myself.
I would like to offer you my solutions.
See the archive with my edits (4 files) in the attachment.
Sorry - comments in the code are in Russian.
Search by string "КДВ"
[hermione.zip](https://github.com/gemini-testing/hermione/files/12060150/hermione.zip)

**Comment by kdenv2604** [comment]
I'm using Windows Desctop Chrome v114

**Comment by DudaGod** [comment]
Hello.

I looked at your archive but didn’t understand anything what you wanted to say in it. Can you provide a minimally reproducible example of the problem? So that I can reproduce the problem locally and understand how it can be fixed.

**Comment by kdenv2604** [comment]
Просто нужна страница, высота которой больше высоты экрана...
Попробуйте снять с неë фулл скрин - проблема должна проявить себя (скрин не
снимется - возникнет ошибка).

Сейчас уже не имею возможности воспроизвести... И ошибка в проекте
исправлена, и другим проектом уже загружен, извините.

Благодарен, что ответили

вт, 10 окт. 2023 г., 18:08 Dmitriy Dudkevich ***@***.***>:

**Comment by DudaGod** [comment]
> Попробуйте снять с неë фулл скрин - проблема должна проявить себя (скрин не снимется - возникнет ошибка). 

Попробовал с последней версией hermione - проблему не воспроизвел. Без проблем снял скриншот 92k px высотой страницы gh с документацией hermione. 

Так как нет минимального воспроизводимого кейсе, то issue закрываю.
