### ISSUE TITLE
Перехватить запросы на внешние ресурсы?

### ISSUE THREAD

**Issue by AdelFattakhova** [gemini-testing/hermione#782]
Столкнулись с тем, что иногда при локальном запуске тестов большинство тест-кейсов падает по таймауту во время исполнения хука `beforeEach`.  Выяснили, что происходит это из-за порой долгой загрузки страницы, которая долгая из-за запросов в сторонние сервисы. Например, разного рода аналитика и реклама.

Есть ли какой-то способ перед началом тестов не ждать полной загрузки страницы, а только DOM, как параметр `waitUntil` в puppeteer и playwright? Пробовали в параметры браузеров ставить `pageLoadStrategy: 'eager'` и `pageLoadStrategy: 'none'` (не помогло):

```js
browsers: {
    chrome: {
      ...
      desiredCapabilities: {
        pageLoadStrategy: 'eager',
        ...
      },
    },
}
```

Или есть ли способ перехватить запросы в сторонние сервисы ДО полной загрузки страницы и подменить ответ (и таким образом не ждать выполнения запросов)? В доке webdriverio нашлись только моки, которые для такого не предназначены (они работают после полной загрузки страницы), и [Interception Service](https://webdriver.io/docs/wdio-intercept-service), который тоже не предоставляет нужного функционала.

**Comment by DudaGod** [comment]
Привет.

> Столкнулись с тем, что иногда при локальном запуске тестов большинство тест-кейсов падает по таймауту во время исполнения хука beforeEach. Выяснили, что происходит это из-за порой долгой загрузки страницы, которая долгая из-за запросов в сторонние сервисы. Например, разного рода аналитика и реклама.

Сайты с аналитикой/рекламой/etc можно замокать и возвращать пустоту. Например вот так:
```
const mock = await this.browser.mock('YOUR_GLOB_MASK'); 
mock.respond('', {fetchResponse: false});
```

В качестве `YOUR_GLOB_MASK` можно подставлять любой сайт в виде строки (например `https://metrika.yandex.ru`) или указать маску вида - `https://www.google.com/images/**/*.png`, т.е. чтобы перехватить все png-шки с google.

> Есть ли какой-то способ перед началом тестов не ждать полной загрузки страницы, а только DOM, как параметр waitUntil в puppeteer и playwright? Пробовали в параметры браузеров ставить pageLoadStrategy: 'eager' и pageLoadStrategy: 'none' (не помогло):

По идее вариант с `pageLoadStrategy: eager` должен работать. Возможно проблема в проверке выполняющейся после открытия урла. Нужен какой-то minimal reproducible example.

> Или есть ли способ перехватить запросы в сторонние сервисы ДО полной загрузки страницы и подменить ответ (и таким образом не ждать выполнения запросов)? В доке webdriverio нашлись только моки, которые для такого не предназначены (они работают после полной загрузки страницы), и [Interception Service](https://webdriver.io/docs/wdio-intercept-service), который тоже не предоставляет нужного функционала.

Моки работают в рантайме, а не после загрузки страницы. Возможно вы забыли явно выставить опцию `fetchResponse: false`, чтобы не осуществлялся реальный запрос.

**Comment by AdelFattakhova** [comment]
да, пропустили `fetchResponse: false`, спасибо!
