### ISSUE TITLE
Как сохранить отчет от Гермионы UI версию?

### ISSUE THREAD

**Issue by swiss-knife-scss** [gemini-testing/hermione#787]
Привет.

Надо сохранить от чет из UI версии Гермионы для передачи.
Нужна именно UI, так как там подписаны страницы и удобно расположены скриншоты.

Как я могу сохранить отчет в данном формате? Или какие есть еще варианты сохранения отчета?

Спасибо!

**Comment by DudaGod** [comment]
Привет.

У плагина html-reporter есть опция `path` - https://github.com/gemini-testing/html-reporter/blob/master/docs/ru/html-reporter-setup.md#path в которую сохраняется отчет со всеми необходимыми файлами (по умолчанию сохраняется в `hermione-report` в корне проекта). 

Открыть отчет можно с помощью команды - `npx http-server hermione-report`. Чтобы открыл какой-то другой пользователь необходимо передать ему папку `hermione-report` и выполнить команды открытия отчета, которую я указал выше.

**Comment by swiss-knife-scss** [comment]
Спасибо большое!
