### ISSUE TITLE
Подключение @wdio/devtools-service

### ISSUE THREAD

**Issue by kirill-lalala** [gemini-testing/hermione#789]
Добрый день, как я могу подключить @wdio/devtools-service? 
Нужна возможность использовать browser.emulateDevice(), но сейчас нет доступа до этого метода, тк не подключен devtools-service. Cоответсвенно ловлю `browser.emulateDevice is not a function`. 
Спасибо

**Comment by DudaGod** [comment]
Привет.

Подключить сервисы wdio к hermione возможности нет. Они подключаются только к wdio раннеру как плагины. В hermione wdio используется просто как API для общения с браузерами.

Логика работы `emulateDevice` 

Все что делает `emulateDevice` так это просто в `desiredCapabilities` поля докидывает.
Код `emulateDevice` - https://github.com/webdriverio/webdriverio/blob/e61e1e4173a77c5bb42b32fba900d5ebfdae75b8/packages/wdio-devtools-service/src/index.ts#L165-L184.
Настройки девайсов берет из puppeteer - https://github.com/puppeteer/puppeteer/blob/c505c85b31eafe4b8e23a080b18887154507a851/packages/puppeteer-core/src/common/Device.ts#L27.

В итоге вместо этого можно написать что-то типа такого:
```
// .hermione.conf.ts

import { KnownDevices } from 'puppeteer-core'

browsers: {
  chrome: {
    desiredCapabilities: {
      browserName: 'chrome',
      browserVersion: '101.0',
      'goog:chromeOptions': {
        mobileEmulation: {
          ...KnownDevices['Pixel 5']
        }
      }
    }
  }
}
```

**Comment by kirill-lalala** [comment]
Спасибо за ответ!
Но что делать если я хочу подменить user-agent только для определенного теста?

**Comment by DudaGod** [comment]
> Но что делать если я хочу подменить user-agent только для определенного теста?

Завести отдельный браузер с необходимым `userAgent` и запускать тест в нем. В рантайме для одного из тестов настройки браузера поменять нельзя.

**Comment by kirill-lalala** [comment]
Благодарю за ответ
