### ISSUE TITLE
Screenshooter

### ISSUE THREAD

**Issue by lemmy-** [gemini-testing/hermione#81]
Hello, guys! Thanks for doing a great job with hermione.
We started using hermione for functional tests in our project and are curious if you have any plans to integrate a screen shooter into hermione? 

Upd: by screen shooter I mean a tool for screen comparison if that make sense :)

**Comment by dfilatov** [comment]
Could anybody answer?

**Comment by sipayRT** [comment]
yes, we discussed it, but this feature does not appear in the near future

**Comment by arikon** [comment]
@lemmy- @dfilatov  We want to port such functionality to Hermione from Gemini. But don't have enough time for it now. Any help is welcome.

Or you could try to use https://github.com/webdriverio/webdrivercss if you can't wait.

**Comment by sergets** [comment]
Hi guys,
I've implemented a custom command to do this (and going to evolve it further):
http://github.com/sergets/hermione-verify-screenshot

I guess it'd be good if we move that repo into `gemini-tesing` org. Would we?

**Comment by j0tunn** [comment]
@sergets Hi. Thanks for your plugin! But while it can be used as an alternative your implementation lacks the some important features:
- calibration
- caret ignoring
- selectors ignoring
- report
- big screenshots support (gluing)
- capturing screenshots on error

Implementing all this stuff would lead to another `gemini`. So I don't think thats our way/ We are thinking about using gemini core here. And this feature should be inside hermione, so I don't think we will move your repo into `gemini-testing` org.

**Comment by stepler** [comment]
Hi guys.
Is there any information about when the integration of the Gemini and Hermione will be done?

**Comment by sipayRT** [comment]
hi
this task is in work (you can see some undocumented commands). But we need more time for it. Maybe few months

**Comment by FriOne** [comment]
@sipayRT Hi, any updates here?

**Comment by sipayRT** [comment]
hi

yes, you can use image assert now - https://github.com/gemini-testing/hermione/blob/master/README.md#assertview
