### ISSUE TITLE
Use Chrome's new Headless mode

### ISSUE THREAD

**Issue by vitaly-kiselev-qa** [gemini-testing/hermione#865]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/gemini-testing/hermione/blob/master/CONTRIBUTING.md))

### Describe the user story

Chrome's Headless mode has got an upgrade recently:
https://developer.chrome.com/docs/chromium/new-headless

It states that the new Headless mode is better for automated tests.
Is it going to be used in Hermione?

I compared the automated test results with [headless](https://github.com/gemini-testing/hermione#headless) option to the results of the `headless=new` test run.
There were significantly less failed tests in the second case .
So it looks like the new Headless mode is much more compatible with the headful mode.

### Describe the solution you'd like

Support the new Chrome's Headless mode.

**Comment by sipayRT** [comment]
Hi

Thank you for the information. I read the description - it sounds really cool. We'll take it in our plans

But right now, instead of using the `headless` option, you can set the desired value in the browser arguments:

```
chrome: {
    desiredCapabilities: {
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: ['--headless=new']
        }
    },
}
```

**Comment by sipayRT** [comment]
you can try it in `hermione@8.5.0`

**Comment by vitaly-kiselev-qa** [comment]
@sipayRT
It works great!
Thank you!
