### ISSUE TITLE
Отсутствуют типы для метода moveCursorTo

### ISSUE THREAD

**Issue by hheimerd** [gemini-testing/hermione#871]
### Verify latest release

* [ ] I verified that the issue exists in the latest Hermione release

### Hermione version

8.3.0

### Reproduction steps

1. npm init hermione-app my-example
2. зайти в hermione-tests/example.hermione.ts
3. добавить внутрь it код  `browser.$("...").moveCursorTo()`

### Describe the Bug

Для временного метода `moveCursorTo` отстутствуют типы. Он был добавлен через `addCommand`, однако типы в PR #842 не были добавлены

### Expected Behavior

Нужно определить типы для этой команды, даже учитывая, что она временная. Так же стоит добавить директиву `@deprecated` с указанием информации об удалении в v9

### Which Node.js version are you using?

20.10.0

**Comment by shadowusr** [comment]
Привет! Спасибо за репорт.

Пофиксил в #876. Добавлены типы для moveCursorTo и openAndWait.

Фикс доступен в версии 8.5.1.
