### ISSUE TITLE
hermione.ctx нельзя типизировать

### ISSUE THREAD

**Issue by hheimerd** [gemini-testing/hermione#883]
### Verify latest release

- [x] I verified that the issue exists in the latest Hermione release

### Hermione version

8.5.0

### Last Hermione version that worked

7.x.x

### Reproduction steps

``` typescript
interface HermioneExtendedContext {
    ctx: {
        someExtendedFn(): void;
    }
}

declare global {
    // Не является глобальным типом, даже если бы являлся, то нельзя переопределить поле
    interface GlobalHelper {
        ctx: HermioneExtendedContext;
    }

    // Глобальные константы нельзя переопределить
    const hermione: {
        ctx: HermioneExtendedContext;
    }
}

hermione.ctx.someExtendedFn (unknown)
```

### Actual Behavior

hermione.ctx нельзя типизировать, все поля явно указаны как unknown. Глобальный объект hermione нельзя расширить

### Expected Behavior

Должен быть способ переопределения типа hermione.ctx и расширения интерфейса GlobalHelper.

Раньше в типах ctx был Record<string, any>, и это не мешало, теперь ctx: Record<string, unknown>, и TS ругается на использование полей ctx без каста. Вставлять везде typeguard - не вариант, слишком много бесполезного кода.
К тому же раньше Hermione.GlobalHelper был глобальным типом и можно было сделать поле extendedCtx, а сейчас это просто экспортированный тип, и его нельзя расширить.

### Which Node.js version are you using?

20.10.0

**Comment by hheimerd** [comment]
Предлагаю сделать откат до варианта с неймспейсом. Или назвать интерфейс HermioneGlobalHelper, если нет желания связываться с неймспейсами.
[плейграунд](https://www.typescriptlang.org/play?#code/FAehAIAEDMEsBsCmA7AhgW0eWyAmiAPAOlyIBcBnYYfAY3lQCcsBzeAewCNV5wBvYOCHg0mCgAdUtLAAlEjdLHbIsA4euzIy86FKwBxDt3hz44+f0EbrAbQDWiAJ4AucBTKMcLALquArsh2yOwA7sgA3FbWAL5R4LHqcbTK7uAAFvKKyoiucgpKKkSGXDym5oyRwLHUdAzM4GwlvGrCoogSeuB5WSqW1kI42oy60uDFxmUWLf3C2u4AFACUrgBu7LC4kTMJwrGxhOLsjGT80ZVgUHBIbZr4xJTUGfnZ5O1kS5FPPYhEAUGhyAAYrBEPBcB8gA)

**Comment by KuznetsovRoman** [comment]
@hheimerd Would #888 satisfy your request?

**Comment by hheimerd** [comment]
Да, идеально
